// Code generated by MockGen. DO NOT EDIT.
// Source: organization.go
//
// Generated by this command:
//
//	mockgen -source organization.go -package mock -destination ./mock/organization.go
//

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	dto "github.com/dedyf5/resik/core/organization/dto"
	ctx "github.com/dedyf5/resik/ctx"
	organization "github.com/dedyf5/resik/entities/organization"
	param "github.com/dedyf5/resik/entities/organization/param"
	response "github.com/dedyf5/resik/pkg/response"
	gomock "go.uber.org/mock/gomock"
)

// MockIService is a mock of IService interface.
type MockIService struct {
	ctrl     *gomock.Controller
	recorder *MockIServiceMockRecorder
	isgomock struct{}
}

// MockIServiceMockRecorder is the mock recorder for MockIService.
type MockIServiceMockRecorder struct {
	mock *MockIService
}

// NewMockIService creates a new mock instance.
func NewMockIService(ctrl *gomock.Controller) *MockIService {
	mock := &MockIService{ctrl: ctrl}
	mock.recorder = &MockIServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIService) EXPECT() *MockIServiceMockRecorder {
	return m.recorder
}

// OrganizationDelete mocks base method.
func (m *MockIService) OrganizationDelete(arg0 *ctx.Ctx, arg1 *organization.Organization) (bool, *response.Status) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OrganizationDelete", arg0, arg1)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(*response.Status)
	return ret0, ret1
}

// OrganizationDelete indicates an expected call of OrganizationDelete.
func (mr *MockIServiceMockRecorder) OrganizationDelete(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OrganizationDelete", reflect.TypeOf((*MockIService)(nil).OrganizationDelete), arg0, arg1)
}

// OrganizationGetByID mocks base method.
func (m *MockIService) OrganizationGetByID(arg0 *ctx.Ctx, organizationID uint64) (*dto.Organization, *response.Status) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OrganizationGetByID", arg0, organizationID)
	ret0, _ := ret[0].(*dto.Organization)
	ret1, _ := ret[1].(*response.Status)
	return ret0, ret1
}

// OrganizationGetByID indicates an expected call of OrganizationGetByID.
func (mr *MockIServiceMockRecorder) OrganizationGetByID(arg0, organizationID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OrganizationGetByID", reflect.TypeOf((*MockIService)(nil).OrganizationGetByID), arg0, organizationID)
}

// OrganizationInsert mocks base method.
func (m *MockIService) OrganizationInsert(arg0 *ctx.Ctx, arg1 *organization.Organization) (bool, *response.Status) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OrganizationInsert", arg0, arg1)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(*response.Status)
	return ret0, ret1
}

// OrganizationInsert indicates an expected call of OrganizationInsert.
func (mr *MockIServiceMockRecorder) OrganizationInsert(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OrganizationInsert", reflect.TypeOf((*MockIService)(nil).OrganizationInsert), arg0, arg1)
}

// OrganizationUpdate mocks base method.
func (m *MockIService) OrganizationUpdate(arg0 *ctx.Ctx, arg1 *organization.Organization) (bool, *response.Status) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OrganizationUpdate", arg0, arg1)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(*response.Status)
	return ret0, ret1
}

// OrganizationUpdate indicates an expected call of OrganizationUpdate.
func (mr *MockIServiceMockRecorder) OrganizationUpdate(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OrganizationUpdate", reflect.TypeOf((*MockIService)(nil).OrganizationUpdate), arg0, arg1)
}

// OrganizationsGet mocks base method.
func (m *MockIService) OrganizationsGet(arg0 *param.OrganizationsGet) (*dto.OrganizationsResult, *response.Status) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OrganizationsGet", arg0)
	ret0, _ := ret[0].(*dto.OrganizationsResult)
	ret1, _ := ret[1].(*response.Status)
	return ret0, ret1
}

// OrganizationsGet indicates an expected call of OrganizationsGet.
func (mr *MockIServiceMockRecorder) OrganizationsGet(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OrganizationsGet", reflect.TypeOf((*MockIService)(nil).OrganizationsGet), arg0)
}
