// Resik
// Author: Dedy Fajar Setyawan
// See: https://github.com/dedyf5/resik

syntax = "proto3";

package response;
option go_package = "github.com/dedyf5/resik/core/merchant/response";

message MerchantList {
    string id = 1; // @gotags: json:"id" example:"019def99a9267f64b75a97b4b19a2c4b"
    string name = 2; // @gotags: json:"name" example:"Resik Merchant"
    string created_at = 3; // @gotags: json:"created_at" example:"2024-01-14T11:40:00Z"
    string updated_at = 4; // @gotags: json:"updated_at" example:"2024-01-14T11:40:00Z"
}
