// Resik
// Author: Dedy Fajar Setyawan
// See: https://github.com/dedyf5/resik

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        v4.25.1
// source: core/merchant/response/upsert.proto

package response

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MerchantUpsert struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID uint64 `protobuf:"varint,1,opt,name=ID,proto3" json:"id" example:"123"`  
}

func (x *MerchantUpsert) Reset() {
	*x = MerchantUpsert{}
	if protoimpl.UnsafeEnabled {
		mi := &file_core_merchant_response_upsert_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MerchantUpsert) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MerchantUpsert) ProtoMessage() {}

func (x *MerchantUpsert) ProtoReflect() protoreflect.Message {
	mi := &file_core_merchant_response_upsert_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MerchantUpsert.ProtoReflect.Descriptor instead.
func (*MerchantUpsert) Descriptor() ([]byte, []int) {
	return file_core_merchant_response_upsert_proto_rawDescGZIP(), []int{0}
}

func (x *MerchantUpsert) GetID() uint64 {
	if x != nil {
		return x.ID
	}
	return 0
}

var File_core_merchant_response_upsert_proto protoreflect.FileDescriptor

var file_core_merchant_response_upsert_proto_rawDesc = []byte{
	0x0a, 0x23, 0x63, 0x6f, 0x72, 0x65, 0x2f, 0x6d, 0x65, 0x72, 0x63, 0x68, 0x61, 0x6e, 0x74, 0x2f,
	0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2f, 0x75, 0x70, 0x73, 0x65, 0x72, 0x74, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x20, 0x0a, 0x0e, 0x4d, 0x65, 0x72, 0x63, 0x68, 0x61, 0x6e, 0x74, 0x55, 0x70, 0x73, 0x65, 0x72,
	0x74, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x49,
	0x44, 0x42, 0x30, 0x5a, 0x2e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x64, 0x65, 0x64, 0x79, 0x66, 0x35, 0x2f, 0x72, 0x65, 0x73, 0x69, 0x6b, 0x2f, 0x63, 0x6f, 0x72,
	0x65, 0x2f, 0x6d, 0x65, 0x72, 0x63, 0x68, 0x61, 0x6e, 0x74, 0x2f, 0x72, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_core_merchant_response_upsert_proto_rawDescOnce sync.Once
	file_core_merchant_response_upsert_proto_rawDescData = file_core_merchant_response_upsert_proto_rawDesc
)

func file_core_merchant_response_upsert_proto_rawDescGZIP() []byte {
	file_core_merchant_response_upsert_proto_rawDescOnce.Do(func() {
		file_core_merchant_response_upsert_proto_rawDescData = protoimpl.X.CompressGZIP(file_core_merchant_response_upsert_proto_rawDescData)
	})
	return file_core_merchant_response_upsert_proto_rawDescData
}

var file_core_merchant_response_upsert_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_core_merchant_response_upsert_proto_goTypes = []interface{}{
	(*MerchantUpsert)(nil), // 0: response.MerchantUpsert
}
var file_core_merchant_response_upsert_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_core_merchant_response_upsert_proto_init() }
func file_core_merchant_response_upsert_proto_init() {
	if File_core_merchant_response_upsert_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_core_merchant_response_upsert_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MerchantUpsert); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_core_merchant_response_upsert_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_core_merchant_response_upsert_proto_goTypes,
		DependencyIndexes: file_core_merchant_response_upsert_proto_depIdxs,
		MessageInfos:      file_core_merchant_response_upsert_proto_msgTypes,
	}.Build()
	File_core_merchant_response_upsert_proto = out.File
	file_core_merchant_response_upsert_proto_rawDesc = nil
	file_core_merchant_response_upsert_proto_goTypes = nil
	file_core_merchant_response_upsert_proto_depIdxs = nil
}
