// Resik
// Author: Dedy Fajar Setyawan
// See: https://github.com/dedyf5/resik

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        v4.25.1
// source: core/app/res/app.proto

package res

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type App struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	App     string   `protobuf:"bytes,1,opt,name=App,proto3" json:"app" example:"Resik REST"`          
	Version string   `protobuf:"bytes,2,opt,name=Version,proto3" json:"version" example:"Version 0.1"`  
	Lang    *AppLang `protobuf:"bytes,3,opt,name=Lang,proto3" json:"lang"`        
}

func (x *App) Reset() {
	*x = App{}
	if protoimpl.UnsafeEnabled {
		mi := &file_core_app_res_app_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *App) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*App) ProtoMessage() {}

func (x *App) ProtoReflect() protoreflect.Message {
	mi := &file_core_app_res_app_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use App.ProtoReflect.Descriptor instead.
func (*App) Descriptor() ([]byte, []int) {
	return file_core_app_res_app_proto_rawDescGZIP(), []int{0}
}

func (x *App) GetApp() string {
	if x != nil {
		return x.App
	}
	return ""
}

func (x *App) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *App) GetLang() *AppLang {
	if x != nil {
		return x.Lang
	}
	return nil
}

type AppLang struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Current string `protobuf:"bytes,1,opt,name=Current,proto3" json:"current" example:"id"`  
	Request string `protobuf:"bytes,2,opt,name=Request,proto3" json:"request" example:"id"`  
	Default string `protobuf:"bytes,3,opt,name=Default,proto3" json:"default" example:"en"`  
}

func (x *AppLang) Reset() {
	*x = AppLang{}
	if protoimpl.UnsafeEnabled {
		mi := &file_core_app_res_app_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AppLang) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppLang) ProtoMessage() {}

func (x *AppLang) ProtoReflect() protoreflect.Message {
	mi := &file_core_app_res_app_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppLang.ProtoReflect.Descriptor instead.
func (*AppLang) Descriptor() ([]byte, []int) {
	return file_core_app_res_app_proto_rawDescGZIP(), []int{1}
}

func (x *AppLang) GetCurrent() string {
	if x != nil {
		return x.Current
	}
	return ""
}

func (x *AppLang) GetRequest() string {
	if x != nil {
		return x.Request
	}
	return ""
}

func (x *AppLang) GetDefault() string {
	if x != nil {
		return x.Default
	}
	return ""
}

var File_core_app_res_app_proto protoreflect.FileDescriptor

var file_core_app_res_app_proto_rawDesc = []byte{
	0x0a, 0x16, 0x63, 0x6f, 0x72, 0x65, 0x2f, 0x61, 0x70, 0x70, 0x2f, 0x72, 0x65, 0x73, 0x2f, 0x61,
	0x70, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x72, 0x65, 0x73, 0x22, 0x53, 0x0a,
	0x03, 0x41, 0x70, 0x70, 0x12, 0x10, 0x0a, 0x03, 0x41, 0x70, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x41, 0x70, 0x70, 0x12, 0x18, 0x0a, 0x07, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f,
	0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e,
	0x12, 0x20, 0x0a, 0x04, 0x4c, 0x61, 0x6e, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c,
	0x2e, 0x72, 0x65, 0x73, 0x2e, 0x41, 0x70, 0x70, 0x4c, 0x61, 0x6e, 0x67, 0x52, 0x04, 0x4c, 0x61,
	0x6e, 0x67, 0x22, 0x57, 0x0a, 0x07, 0x41, 0x70, 0x70, 0x4c, 0x61, 0x6e, 0x67, 0x12, 0x18, 0x0a,
	0x07, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x18, 0x0a, 0x07, 0x44, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x44, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x42, 0x26, 0x5a, 0x24, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x64, 0x65, 0x64, 0x79, 0x66, 0x35,
	0x2f, 0x72, 0x65, 0x73, 0x69, 0x6b, 0x2f, 0x63, 0x6f, 0x72, 0x65, 0x2f, 0x61, 0x70, 0x70, 0x2f,
	0x72, 0x65, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_core_app_res_app_proto_rawDescOnce sync.Once
	file_core_app_res_app_proto_rawDescData = file_core_app_res_app_proto_rawDesc
)

func file_core_app_res_app_proto_rawDescGZIP() []byte {
	file_core_app_res_app_proto_rawDescOnce.Do(func() {
		file_core_app_res_app_proto_rawDescData = protoimpl.X.CompressGZIP(file_core_app_res_app_proto_rawDescData)
	})
	return file_core_app_res_app_proto_rawDescData
}

var file_core_app_res_app_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_core_app_res_app_proto_goTypes = []interface{}{
	(*App)(nil),     // 0: res.App
	(*AppLang)(nil), // 1: res.AppLang
}
var file_core_app_res_app_proto_depIdxs = []int32{
	1, // 0: res.App.Lang:type_name -> res.AppLang
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_core_app_res_app_proto_init() }
func file_core_app_res_app_proto_init() {
	if File_core_app_res_app_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_core_app_res_app_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*App); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_core_app_res_app_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AppLang); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_core_app_res_app_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_core_app_res_app_proto_goTypes,
		DependencyIndexes: file_core_app_res_app_proto_depIdxs,
		MessageInfos:      file_core_app_res_app_proto_msgTypes,
	}.Build()
	File_core_app_res_app_proto = out.File
	file_core_app_res_app_proto_rawDesc = nil
	file_core_app_res_app_proto_goTypes = nil
	file_core_app_res_app_proto_depIdxs = nil
}
