// Resik
// Author: Dedy Fajar Setyawan
// See: https://github.com/dedyf5/resik

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v4.25.1
// source: core/common/status_and_id.proto

package common

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Message status and id
type StatusAndId struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status *Status `protobuf:"bytes,1,opt,name=status,proto3" json:"status"`  
	Data   *Id     `protobuf:"bytes,2,opt,name=data,proto3" json:"data"`      
}

func (x *StatusAndId) Reset() {
	*x = StatusAndId{}
	if protoimpl.UnsafeEnabled {
		mi := &file_core_common_status_and_id_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StatusAndId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusAndId) ProtoMessage() {}

func (x *StatusAndId) ProtoReflect() protoreflect.Message {
	mi := &file_core_common_status_and_id_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusAndId.ProtoReflect.Descriptor instead.
func (*StatusAndId) Descriptor() ([]byte, []int) {
	return file_core_common_status_and_id_proto_rawDescGZIP(), []int{0}
}

func (x *StatusAndId) GetStatus() *Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *StatusAndId) GetData() *Id {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_core_common_status_and_id_proto protoreflect.FileDescriptor

var file_core_common_status_and_id_proto_rawDesc = []byte{
	0x0a, 0x1f, 0x63, 0x6f, 0x72, 0x65, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x5f, 0x61, 0x6e, 0x64, 0x5f, 0x69, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x0b, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x1a, 0x18,
	0x63, 0x6f, 0x72, 0x65, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x14, 0x63, 0x6f, 0x72, 0x65, 0x2f, 0x63,
	0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x69, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x5f,
	0x0a, 0x0b, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x41, 0x6e, 0x64, 0x49, 0x64, 0x12, 0x2b, 0x0a,
	0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e,
	0x63, 0x6f, 0x72, 0x65, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x23, 0x0a, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x2e,
	0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x49, 0x64, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x42,
	0x25, 0x5a, 0x23, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x64, 0x65,
	0x64, 0x79, 0x66, 0x35, 0x2f, 0x72, 0x65, 0x73, 0x69, 0x6b, 0x2f, 0x63, 0x6f, 0x72, 0x65, 0x2f,
	0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_core_common_status_and_id_proto_rawDescOnce sync.Once
	file_core_common_status_and_id_proto_rawDescData = file_core_common_status_and_id_proto_rawDesc
)

func file_core_common_status_and_id_proto_rawDescGZIP() []byte {
	file_core_common_status_and_id_proto_rawDescOnce.Do(func() {
		file_core_common_status_and_id_proto_rawDescData = protoimpl.X.CompressGZIP(file_core_common_status_and_id_proto_rawDescData)
	})
	return file_core_common_status_and_id_proto_rawDescData
}

var file_core_common_status_and_id_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_core_common_status_and_id_proto_goTypes = []any{
	(*StatusAndId)(nil), // 0: core.common.StatusAndId
	(*Status)(nil),      // 1: core.common.Status
	(*Id)(nil),          // 2: core.common.Id
}
var file_core_common_status_and_id_proto_depIdxs = []int32{
	1, // 0: core.common.StatusAndId.status:type_name -> core.common.Status
	2, // 1: core.common.StatusAndId.data:type_name -> core.common.Id
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_core_common_status_and_id_proto_init() }
func file_core_common_status_and_id_proto_init() {
	if File_core_common_status_and_id_proto != nil {
		return
	}
	file_core_common_status_proto_init()
	file_core_common_id_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_core_common_status_and_id_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*StatusAndId); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_core_common_status_and_id_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_core_common_status_and_id_proto_goTypes,
		DependencyIndexes: file_core_common_status_and_id_proto_depIdxs,
		MessageInfos:      file_core_common_status_and_id_proto_msgTypes,
	}.Build()
	File_core_common_status_and_id_proto = out.File
	file_core_common_status_and_id_proto_rawDesc = nil
	file_core_common_status_and_id_proto_goTypes = nil
	file_core_common_status_and_id_proto_depIdxs = nil
}
