// Resik
// Author: Dedy Fajar Setyawan
// See: https://github.com/dedyf5/resik

syntax = "proto3";

package core.transaction.request;
option go_package = "github.com/dedyf5/resik/core/transaction/request";

message TransactionListGet {
    string search = 1; // @gotags: json:"search" query:"search" validate:"" example:"keyword"
    optional string order = 2; // @gotags: json:"order" query:"order" validate:"omitempty,oneof_order=branch_name organization_name bill_total transacted_at"
    optional int32 page = 3; // @gotags: json:"page" query:"page" validate:"omitempty,min=1" example:"1"
    optional int32 limit = 4; // @gotags: json:"limit" query:"limit" validate:"omitempty,min=1" example:"10"
}
