// Resik
// Author: Dedy Fajar Setyawan
// See: https://github.com/dedyf5/resik

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        v4.25.1
// source: core/transaction/request/merchant.proto

package request

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MerchantOmzetGet struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MerchantID    uint64  `protobuf:"varint,1,opt,name=MerchantID,proto3" json:"-" param:"id" query:"-" validate:"required,min=1" example:"1"`       
	Mode          string  `protobuf:"bytes,2,opt,name=Mode,proto3" json:"mode" query:"mode" validate:"required,oneof=day month year" example:"day"`                    
	DateTimeStart string  `protobuf:"bytes,3,opt,name=DateTimeStart,proto3" json:"datetime_start" query:"datetime_start" validate:"required,datetime=2006-01-02 15:04:05" example:"2023-11-22 13:45:00"`  
	DateTimeEnd   string  `protobuf:"bytes,4,opt,name=DateTimeEnd,proto3" json:"datetime_end" query:"datetime_end" validate:"required,datetime=2006-01-02 15:04:05" example:"2023-11-22 13:45:00"`      
	Search        string  `protobuf:"bytes,5,opt,name=Search,proto3" json:"search" query:"search" example:"keyword"`                
	Order         *string `protobuf:"bytes,6,opt,name=Order,proto3,oneof" json:"order" query:"order" validate:"omitempty,oneof_order=period omzet merchant_name" example:"period"`            
	Page          *uint32 `protobuf:"varint,7,opt,name=Page,proto3,oneof" json:"page" query:"page" validate:"omitempty,min=1" example:"1"`             
	Limit         *uint32 `protobuf:"varint,8,opt,name=Limit,proto3,oneof" json:"limit" query:"limit" validate:"omitempty,min=1,max=100" example:"10"`           
}

func (x *MerchantOmzetGet) Reset() {
	*x = MerchantOmzetGet{}
	if protoimpl.UnsafeEnabled {
		mi := &file_core_transaction_request_merchant_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MerchantOmzetGet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MerchantOmzetGet) ProtoMessage() {}

func (x *MerchantOmzetGet) ProtoReflect() protoreflect.Message {
	mi := &file_core_transaction_request_merchant_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MerchantOmzetGet.ProtoReflect.Descriptor instead.
func (*MerchantOmzetGet) Descriptor() ([]byte, []int) {
	return file_core_transaction_request_merchant_proto_rawDescGZIP(), []int{0}
}

func (x *MerchantOmzetGet) GetMerchantID() uint64 {
	if x != nil {
		return x.MerchantID
	}
	return 0
}

func (x *MerchantOmzetGet) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *MerchantOmzetGet) GetDateTimeStart() string {
	if x != nil {
		return x.DateTimeStart
	}
	return ""
}

func (x *MerchantOmzetGet) GetDateTimeEnd() string {
	if x != nil {
		return x.DateTimeEnd
	}
	return ""
}

func (x *MerchantOmzetGet) GetSearch() string {
	if x != nil {
		return x.Search
	}
	return ""
}

func (x *MerchantOmzetGet) GetOrder() string {
	if x != nil && x.Order != nil {
		return *x.Order
	}
	return ""
}

func (x *MerchantOmzetGet) GetPage() uint32 {
	if x != nil && x.Page != nil {
		return *x.Page
	}
	return 0
}

func (x *MerchantOmzetGet) GetLimit() uint32 {
	if x != nil && x.Limit != nil {
		return *x.Limit
	}
	return 0
}

var File_core_transaction_request_merchant_proto protoreflect.FileDescriptor

var file_core_transaction_request_merchant_proto_rawDesc = []byte{
	0x0a, 0x27, 0x63, 0x6f, 0x72, 0x65, 0x2f, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x2f, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2f, 0x6d, 0x65, 0x72, 0x63, 0x68,
	0x61, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x72, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x22, 0x92, 0x02, 0x0a, 0x10, 0x4d, 0x65, 0x72, 0x63, 0x68, 0x61, 0x6e, 0x74, 0x4f,
	0x6d, 0x7a, 0x65, 0x74, 0x47, 0x65, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x4d, 0x65, 0x72, 0x63, 0x68,
	0x61, 0x6e, 0x74, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0a, 0x4d, 0x65, 0x72,
	0x63, 0x68, 0x61, 0x6e, 0x74, 0x49, 0x44, 0x12, 0x12, 0x0a, 0x04, 0x4d, 0x6f, 0x64, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4d, 0x6f, 0x64, 0x65, 0x12, 0x24, 0x0a, 0x0d, 0x44,
	0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x72, 0x74, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0d, 0x44, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x72,
	0x74, 0x12, 0x20, 0x0a, 0x0b, 0x44, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x45, 0x6e, 0x64,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x44, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65,
	0x45, 0x6e, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x12, 0x19, 0x0a, 0x05, 0x4f,
	0x72, 0x64, 0x65, 0x72, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x05, 0x4f, 0x72,
	0x64, 0x65, 0x72, 0x88, 0x01, 0x01, 0x12, 0x17, 0x0a, 0x04, 0x50, 0x61, 0x67, 0x65, 0x18, 0x07,
	0x20, 0x01, 0x28, 0x0d, 0x48, 0x01, 0x52, 0x04, 0x50, 0x61, 0x67, 0x65, 0x88, 0x01, 0x01, 0x12,
	0x19, 0x0a, 0x05, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0d, 0x48, 0x02,
	0x52, 0x05, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x88, 0x01, 0x01, 0x42, 0x08, 0x0a, 0x06, 0x5f, 0x4f,
	0x72, 0x64, 0x65, 0x72, 0x42, 0x07, 0x0a, 0x05, 0x5f, 0x50, 0x61, 0x67, 0x65, 0x42, 0x08, 0x0a,
	0x06, 0x5f, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x42, 0x32, 0x5a, 0x30, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x64, 0x65, 0x64, 0x79, 0x66, 0x35, 0x2f, 0x72, 0x65, 0x73,
	0x69, 0x6b, 0x2f, 0x63, 0x6f, 0x72, 0x65, 0x2f, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x2f, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_core_transaction_request_merchant_proto_rawDescOnce sync.Once
	file_core_transaction_request_merchant_proto_rawDescData = file_core_transaction_request_merchant_proto_rawDesc
)

func file_core_transaction_request_merchant_proto_rawDescGZIP() []byte {
	file_core_transaction_request_merchant_proto_rawDescOnce.Do(func() {
		file_core_transaction_request_merchant_proto_rawDescData = protoimpl.X.CompressGZIP(file_core_transaction_request_merchant_proto_rawDescData)
	})
	return file_core_transaction_request_merchant_proto_rawDescData
}

var file_core_transaction_request_merchant_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_core_transaction_request_merchant_proto_goTypes = []interface{}{
	(*MerchantOmzetGet)(nil), // 0: request.MerchantOmzetGet
}
var file_core_transaction_request_merchant_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_core_transaction_request_merchant_proto_init() }
func file_core_transaction_request_merchant_proto_init() {
	if File_core_transaction_request_merchant_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_core_transaction_request_merchant_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MerchantOmzetGet); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_core_transaction_request_merchant_proto_msgTypes[0].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_core_transaction_request_merchant_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_core_transaction_request_merchant_proto_goTypes,
		DependencyIndexes: file_core_transaction_request_merchant_proto_depIdxs,
		MessageInfos:      file_core_transaction_request_merchant_proto_msgTypes,
	}.Build()
	File_core_transaction_request_merchant_proto = out.File
	file_core_transaction_request_merchant_proto_rawDesc = nil
	file_core_transaction_request_merchant_proto_goTypes = nil
	file_core_transaction_request_merchant_proto_depIdxs = nil
}
