// Resik
// Author: Dedy Fajar Setyawan
// See: https://github.com/dedyf5/resik

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v4.25.1
// source: core/transaction/request/upsert.proto

package request

import (
	common "github.com/dedyf5/resik/core/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Message request to create a transaction
type TransactionPost struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Branch       *common.Branch `protobuf:"bytes,1,opt,name=branch,proto3" json:"branch" validate:"required"`                                  
	BillTotal    *float64       `protobuf:"fixed64,2,opt,name=bill_total,json=billTotal,proto3,oneof" json:"bill_total" validate:"required,gte=0" example:"1000.5"`   
	TransactedAt string         `protobuf:"bytes,3,opt,name=transacted_at,json=transactedAt,proto3" json:"transacted_at" validate:"required,datetime=2006-01-02T15:04:05Z07:00,past_or_present" example:"2024-02-02T19:52:41Z"`  
}

func (x *TransactionPost) Reset() {
	*x = TransactionPost{}
	if protoimpl.UnsafeEnabled {
		mi := &file_core_transaction_request_upsert_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TransactionPost) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionPost) ProtoMessage() {}

func (x *TransactionPost) ProtoReflect() protoreflect.Message {
	mi := &file_core_transaction_request_upsert_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionPost.ProtoReflect.Descriptor instead.
func (*TransactionPost) Descriptor() ([]byte, []int) {
	return file_core_transaction_request_upsert_proto_rawDescGZIP(), []int{0}
}

func (x *TransactionPost) GetBranch() *common.Branch {
	if x != nil {
		return x.Branch
	}
	return nil
}

func (x *TransactionPost) GetBillTotal() float64 {
	if x != nil && x.BillTotal != nil {
		return *x.BillTotal
	}
	return 0
}

func (x *TransactionPost) GetTransactedAt() string {
	if x != nil {
		return x.TransactedAt
	}
	return ""
}

var File_core_transaction_request_upsert_proto protoreflect.FileDescriptor

var file_core_transaction_request_upsert_proto_rawDesc = []byte{
	0x0a, 0x25, 0x63, 0x6f, 0x72, 0x65, 0x2f, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x2f, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2f, 0x75, 0x70, 0x73, 0x65, 0x72,
	0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x18, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x74, 0x72,
	0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x16, 0x63, 0x6f, 0x72, 0x65, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x75,
	0x73, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1e, 0x63, 0x6f, 0x72, 0x65, 0x2f,
	0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x6f, 0x72, 0x67, 0x61, 0x6e, 0x69, 0x7a, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x96, 0x01, 0x0a, 0x0f, 0x54, 0x72,
	0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x50, 0x6f, 0x73, 0x74, 0x12, 0x2b, 0x0a,
	0x06, 0x62, 0x72, 0x61, 0x6e, 0x63, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e,
	0x63, 0x6f, 0x72, 0x65, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x42, 0x72, 0x61, 0x6e,
	0x63, 0x68, 0x52, 0x06, 0x62, 0x72, 0x61, 0x6e, 0x63, 0x68, 0x12, 0x22, 0x0a, 0x0a, 0x62, 0x69,
	0x6c, 0x6c, 0x5f, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x48, 0x00,
	0x52, 0x09, 0x62, 0x69, 0x6c, 0x6c, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x88, 0x01, 0x01, 0x12, 0x23,
	0x0a, 0x0d, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x65,
	0x64, 0x41, 0x74, 0x42, 0x0d, 0x0a, 0x0b, 0x5f, 0x62, 0x69, 0x6c, 0x6c, 0x5f, 0x74, 0x6f, 0x74,
	0x61, 0x6c, 0x42, 0x32, 0x5a, 0x30, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x64, 0x65, 0x64, 0x79, 0x66, 0x35, 0x2f, 0x72, 0x65, 0x73, 0x69, 0x6b, 0x2f, 0x63, 0x6f,
	0x72, 0x65, 0x2f, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2f, 0x72,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_core_transaction_request_upsert_proto_rawDescOnce sync.Once
	file_core_transaction_request_upsert_proto_rawDescData = file_core_transaction_request_upsert_proto_rawDesc
)

func file_core_transaction_request_upsert_proto_rawDescGZIP() []byte {
	file_core_transaction_request_upsert_proto_rawDescOnce.Do(func() {
		file_core_transaction_request_upsert_proto_rawDescData = protoimpl.X.CompressGZIP(file_core_transaction_request_upsert_proto_rawDescData)
	})
	return file_core_transaction_request_upsert_proto_rawDescData
}

var file_core_transaction_request_upsert_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_core_transaction_request_upsert_proto_goTypes = []any{
	(*TransactionPost)(nil), // 0: core.transaction.request.TransactionPost
	(*common.Branch)(nil),   // 1: core.common.Branch
}
var file_core_transaction_request_upsert_proto_depIdxs = []int32{
	1, // 0: core.transaction.request.TransactionPost.branch:type_name -> core.common.Branch
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_core_transaction_request_upsert_proto_init() }
func file_core_transaction_request_upsert_proto_init() {
	if File_core_transaction_request_upsert_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_core_transaction_request_upsert_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*TransactionPost); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_core_transaction_request_upsert_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_core_transaction_request_upsert_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_core_transaction_request_upsert_proto_goTypes,
		DependencyIndexes: file_core_transaction_request_upsert_proto_depIdxs,
		MessageInfos:      file_core_transaction_request_upsert_proto_msgTypes,
	}.Build()
	File_core_transaction_request_upsert_proto = out.File
	file_core_transaction_request_upsert_proto_rawDesc = nil
	file_core_transaction_request_upsert_proto_goTypes = nil
	file_core_transaction_request_upsert_proto_depIdxs = nil
}
