// Code generated by MockGen. DO NOT EDIT.
// Source: contract.go
//
// Generated by this command:
//
//	mockgen -source contract.go -package identity -destination ./mock/identity_resolver.go
//

// Package identity is a generated GoMock package.
package identity

import (
	context "context"
	reflect "reflect"

	uuid "github.com/dedyf5/resik/pkg/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockIdentityResolver is a mock of IdentityResolver interface.
type MockIdentityResolver struct {
	ctrl     *gomock.Controller
	recorder *MockIdentityResolverMockRecorder
	isgomock struct{}
}

// MockIdentityResolverMockRecorder is the mock recorder for MockIdentityResolver.
type MockIdentityResolverMockRecorder struct {
	mock *MockIdentityResolver
}

// NewMockIdentityResolver creates a new mock instance.
func NewMockIdentityResolver(ctrl *gomock.Controller) *MockIdentityResolver {
	mock := &MockIdentityResolver{ctrl: ctrl}
	mock.recorder = &MockIdentityResolverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIdentityResolver) EXPECT() *MockIdentityResolverMockRecorder {
	return m.recorder
}

// Resolve mocks base method.
func (m *MockIdentityResolver) Resolve(c context.Context, tableName string, publicID uuid.UUIDV7) (uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Resolve", c, tableName, publicID)
	ret0, _ := ret[0].(uint64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Resolve indicates an expected call of Resolve.
func (mr *MockIdentityResolverMockRecorder) Resolve(c, tableName, publicID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Resolve", reflect.TypeOf((*MockIdentityResolver)(nil).Resolve), c, tableName, publicID)
}

// ResolveBatch mocks base method.
func (m *MockIdentityResolver) ResolveBatch(c context.Context, tableName string, publicIDs []uuid.UUIDV7) ([]uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResolveBatch", c, tableName, publicIDs)
	ret0, _ := ret[0].([]uint64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ResolveBatch indicates an expected call of ResolveBatch.
func (mr *MockIdentityResolverMockRecorder) ResolveBatch(c, tableName, publicIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResolveBatch", reflect.TypeOf((*MockIdentityResolver)(nil).ResolveBatch), c, tableName, publicIDs)
}
