// Code generated by MockGen. DO NOT EDIT.
// Source: contract.go
//
// Generated by this command:
//
//	mockgen -source contract.go -package identity -destination ./mock/identity_resolver.go
//

// Package identity is a generated GoMock package.
package identity

import (
	context "context"
	reflect "reflect"

	uuid "github.com/dedyf5/resik/pkg/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockIdentityResolver is a mock of IdentityResolver interface.
type MockIdentityResolver struct {
	ctrl     *gomock.Controller
	recorder *MockIdentityResolverMockRecorder
	isgomock struct{}
}

// MockIdentityResolverMockRecorder is the mock recorder for MockIdentityResolver.
type MockIdentityResolverMockRecorder struct {
	mock *MockIdentityResolver
}

// NewMockIdentityResolver creates a new mock instance.
func NewMockIdentityResolver(ctrl *gomock.Controller) *MockIdentityResolver {
	mock := &MockIdentityResolver{ctrl: ctrl}
	mock.recorder = &MockIdentityResolverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIdentityResolver) EXPECT() *MockIdentityResolverMockRecorder {
	return m.recorder
}

// GetMerchantIDsByPermission mocks base method.
func (m *MockIdentityResolver) GetMerchantIDsByPermission(c context.Context, userID uint64, permissionCode string) ([]uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMerchantIDsByPermission", c, userID, permissionCode)
	ret0, _ := ret[0].([]uint64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMerchantIDsByPermission indicates an expected call of GetMerchantIDsByPermission.
func (mr *MockIdentityResolverMockRecorder) GetMerchantIDsByPermission(c, userID, permissionCode any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMerchantIDsByPermission", reflect.TypeOf((*MockIdentityResolver)(nil).GetMerchantIDsByPermission), c, userID, permissionCode)
}

// GetOutletIDsByPermission mocks base method.
func (m *MockIdentityResolver) GetOutletIDsByPermission(c context.Context, userID uint64, permissionCode string) ([]uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOutletIDsByPermission", c, userID, permissionCode)
	ret0, _ := ret[0].([]uint64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOutletIDsByPermission indicates an expected call of GetOutletIDsByPermission.
func (mr *MockIdentityResolverMockRecorder) GetOutletIDsByPermission(c, userID, permissionCode any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOutletIDsByPermission", reflect.TypeOf((*MockIdentityResolver)(nil).GetOutletIDsByPermission), c, userID, permissionCode)
}

// GetResourceIDs mocks base method.
func (m *MockIdentityResolver) GetResourceIDs(c context.Context, userID uint64, resourceTable, permissionCode string) ([]uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetResourceIDs", c, userID, resourceTable, permissionCode)
	ret0, _ := ret[0].([]uint64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetResourceIDs indicates an expected call of GetResourceIDs.
func (mr *MockIdentityResolverMockRecorder) GetResourceIDs(c, userID, resourceTable, permissionCode any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetResourceIDs", reflect.TypeOf((*MockIdentityResolver)(nil).GetResourceIDs), c, userID, resourceTable, permissionCode)
}

// GetTenantMerchantIDs mocks base method.
func (m *MockIdentityResolver) GetTenantMerchantIDs(c context.Context, userID uint64) ([]uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTenantMerchantIDs", c, userID)
	ret0, _ := ret[0].([]uint64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTenantMerchantIDs indicates an expected call of GetTenantMerchantIDs.
func (mr *MockIdentityResolverMockRecorder) GetTenantMerchantIDs(c, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTenantMerchantIDs", reflect.TypeOf((*MockIdentityResolver)(nil).GetTenantMerchantIDs), c, userID)
}

// GetTenantOutletIDs mocks base method.
func (m *MockIdentityResolver) GetTenantOutletIDs(c context.Context, userID uint64) ([]uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTenantOutletIDs", c, userID)
	ret0, _ := ret[0].([]uint64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTenantOutletIDs indicates an expected call of GetTenantOutletIDs.
func (mr *MockIdentityResolverMockRecorder) GetTenantOutletIDs(c, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTenantOutletIDs", reflect.TypeOf((*MockIdentityResolver)(nil).GetTenantOutletIDs), c, userID)
}

// HasAccessByID mocks base method.
func (m *MockIdentityResolver) HasAccessByID(c context.Context, userID uint64, permissionCode, resourceTable string, resourceID uint64) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasAccessByID", c, userID, permissionCode, resourceTable, resourceID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HasAccessByID indicates an expected call of HasAccessByID.
func (mr *MockIdentityResolverMockRecorder) HasAccessByID(c, userID, permissionCode, resourceTable, resourceID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasAccessByID", reflect.TypeOf((*MockIdentityResolver)(nil).HasAccessByID), c, userID, permissionCode, resourceTable, resourceID)
}

// HasAccessByPublicID mocks base method.
func (m *MockIdentityResolver) HasAccessByPublicID(c context.Context, userID uint64, permissionCode, resourceTable string, publicID uuid.UUIDV7) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasAccessByPublicID", c, userID, permissionCode, resourceTable, publicID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HasAccessByPublicID indicates an expected call of HasAccessByPublicID.
func (mr *MockIdentityResolverMockRecorder) HasAccessByPublicID(c, userID, permissionCode, resourceTable, publicID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasAccessByPublicID", reflect.TypeOf((*MockIdentityResolver)(nil).HasAccessByPublicID), c, userID, permissionCode, resourceTable, publicID)
}

// InvalidateUserAccessMerchant mocks base method.
func (m *MockIdentityResolver) InvalidateUserAccessMerchant(ctx context.Context, userID uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InvalidateUserAccessMerchant", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// InvalidateUserAccessMerchant indicates an expected call of InvalidateUserAccessMerchant.
func (mr *MockIdentityResolverMockRecorder) InvalidateUserAccessMerchant(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InvalidateUserAccessMerchant", reflect.TypeOf((*MockIdentityResolver)(nil).InvalidateUserAccessMerchant), ctx, userID)
}

// InvalidateUserAccessOutlet mocks base method.
func (m *MockIdentityResolver) InvalidateUserAccessOutlet(ctx context.Context, userID uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InvalidateUserAccessOutlet", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// InvalidateUserAccessOutlet indicates an expected call of InvalidateUserAccessOutlet.
func (mr *MockIdentityResolverMockRecorder) InvalidateUserAccessOutlet(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InvalidateUserAccessOutlet", reflect.TypeOf((*MockIdentityResolver)(nil).InvalidateUserAccessOutlet), ctx, userID)
}

// Resolve mocks base method.
func (m *MockIdentityResolver) Resolve(c context.Context, tableName string, publicID uuid.UUIDV7) (uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Resolve", c, tableName, publicID)
	ret0, _ := ret[0].(uint64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Resolve indicates an expected call of Resolve.
func (mr *MockIdentityResolverMockRecorder) Resolve(c, tableName, publicID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Resolve", reflect.TypeOf((*MockIdentityResolver)(nil).Resolve), c, tableName, publicID)
}

// ResolveBatch mocks base method.
func (m *MockIdentityResolver) ResolveBatch(c context.Context, tableName string, publicIDs []uuid.UUIDV7) ([]uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResolveBatch", c, tableName, publicIDs)
	ret0, _ := ret[0].([]uint64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ResolveBatch indicates an expected call of ResolveBatch.
func (mr *MockIdentityResolverMockRecorder) ResolveBatch(c, tableName, publicIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResolveBatch", reflect.TypeOf((*MockIdentityResolver)(nil).ResolveBatch), c, tableName, publicIDs)
}
