// Resik
// Author: Dedy Fajar Setyawan
// See: https://github.com/dedyf5/resik

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        v4.25.1
// source: core/health/response/readyz.proto

package response

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HealthReadyz struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OverallStatus string               `protobuf:"bytes,1,opt,name=OverallStatus,proto3" json:"overall_status" example:"UP"`  
	Checks        []*HealthReadyzCheck `protobuf:"bytes,2,rep,name=Checks,proto3" json:"checks"`                
	AccessedAt    string               `protobuf:"bytes,3,opt,name=AccessedAt,proto3" json:"accessed_at" example:"2025-06-14 16:42:00"`        
}

func (x *HealthReadyz) Reset() {
	*x = HealthReadyz{}
	if protoimpl.UnsafeEnabled {
		mi := &file_core_health_response_readyz_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HealthReadyz) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthReadyz) ProtoMessage() {}

func (x *HealthReadyz) ProtoReflect() protoreflect.Message {
	mi := &file_core_health_response_readyz_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthReadyz.ProtoReflect.Descriptor instead.
func (*HealthReadyz) Descriptor() ([]byte, []int) {
	return file_core_health_response_readyz_proto_rawDescGZIP(), []int{0}
}

func (x *HealthReadyz) GetOverallStatus() string {
	if x != nil {
		return x.OverallStatus
	}
	return ""
}

func (x *HealthReadyz) GetChecks() []*HealthReadyzCheck {
	if x != nil {
		return x.Checks
	}
	return nil
}

func (x *HealthReadyz) GetAccessedAt() string {
	if x != nil {
		return x.AccessedAt
	}
	return ""
}

type HealthReadyzCheck struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name   string  `protobuf:"bytes,1,opt,name=name,proto3" json:"name"`          
	Status string  `protobuf:"bytes,2,opt,name=status,proto3" json:"status" example:"UP"`      
	Error  *string `protobuf:"bytes,3,opt,name=Error,proto3,oneof" json:"error"`  
}

func (x *HealthReadyzCheck) Reset() {
	*x = HealthReadyzCheck{}
	if protoimpl.UnsafeEnabled {
		mi := &file_core_health_response_readyz_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HealthReadyzCheck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthReadyzCheck) ProtoMessage() {}

func (x *HealthReadyzCheck) ProtoReflect() protoreflect.Message {
	mi := &file_core_health_response_readyz_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthReadyzCheck.ProtoReflect.Descriptor instead.
func (*HealthReadyzCheck) Descriptor() ([]byte, []int) {
	return file_core_health_response_readyz_proto_rawDescGZIP(), []int{1}
}

func (x *HealthReadyzCheck) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *HealthReadyzCheck) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthReadyzCheck) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

var File_core_health_response_readyz_proto protoreflect.FileDescriptor

var file_core_health_response_readyz_proto_rawDesc = []byte{
	0x0a, 0x21, 0x63, 0x6f, 0x72, 0x65, 0x2f, 0x68, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x2f, 0x72, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2f, 0x72, 0x65, 0x61, 0x64, 0x79, 0x7a, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x89, 0x01,
	0x0a, 0x0c, 0x48, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x52, 0x65, 0x61, 0x64, 0x79, 0x7a, 0x12, 0x24,
	0x0a, 0x0d, 0x4f, 0x76, 0x65, 0x72, 0x61, 0x6c, 0x6c, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x4f, 0x76, 0x65, 0x72, 0x61, 0x6c, 0x6c, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x12, 0x33, 0x0a, 0x06, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x73, 0x18, 0x02,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e,
	0x48, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x52, 0x65, 0x61, 0x64, 0x79, 0x7a, 0x43, 0x68, 0x65, 0x63,
	0x6b, 0x52, 0x06, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x73, 0x12, 0x1e, 0x0a, 0x0a, 0x41, 0x63, 0x63,
	0x65, 0x73, 0x73, 0x65, 0x64, 0x41, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x41,
	0x63, 0x63, 0x65, 0x73, 0x73, 0x65, 0x64, 0x41, 0x74, 0x22, 0x64, 0x0a, 0x11, 0x48, 0x65, 0x61,
	0x6c, 0x74, 0x68, 0x52, 0x65, 0x61, 0x64, 0x79, 0x7a, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x19, 0x0a, 0x05, 0x45, 0x72,
	0x72, 0x6f, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x05, 0x45, 0x72, 0x72,
	0x6f, 0x72, 0x88, 0x01, 0x01, 0x42, 0x08, 0x0a, 0x06, 0x5f, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x42,
	0x2e, 0x5a, 0x2c, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x64, 0x65,
	0x64, 0x79, 0x66, 0x35, 0x2f, 0x72, 0x65, 0x73, 0x69, 0x6b, 0x2f, 0x63, 0x6f, 0x72, 0x65, 0x2f,
	0x68, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x2f, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_core_health_response_readyz_proto_rawDescOnce sync.Once
	file_core_health_response_readyz_proto_rawDescData = file_core_health_response_readyz_proto_rawDesc
)

func file_core_health_response_readyz_proto_rawDescGZIP() []byte {
	file_core_health_response_readyz_proto_rawDescOnce.Do(func() {
		file_core_health_response_readyz_proto_rawDescData = protoimpl.X.CompressGZIP(file_core_health_response_readyz_proto_rawDescData)
	})
	return file_core_health_response_readyz_proto_rawDescData
}

var file_core_health_response_readyz_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_core_health_response_readyz_proto_goTypes = []interface{}{
	(*HealthReadyz)(nil),      // 0: response.HealthReadyz
	(*HealthReadyzCheck)(nil), // 1: response.HealthReadyzCheck
}
var file_core_health_response_readyz_proto_depIdxs = []int32{
	1, // 0: response.HealthReadyz.Checks:type_name -> response.HealthReadyzCheck
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_core_health_response_readyz_proto_init() }
func file_core_health_response_readyz_proto_init() {
	if File_core_health_response_readyz_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_core_health_response_readyz_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HealthReadyz); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_core_health_response_readyz_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HealthReadyzCheck); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_core_health_response_readyz_proto_msgTypes[1].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_core_health_response_readyz_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_core_health_response_readyz_proto_goTypes,
		DependencyIndexes: file_core_health_response_readyz_proto_depIdxs,
		MessageInfos:      file_core_health_response_readyz_proto_msgTypes,
	}.Build()
	File_core_health_response_readyz_proto = out.File
	file_core_health_response_readyz_proto_rawDesc = nil
	file_core_health_response_readyz_proto_goTypes = nil
	file_core_health_response_readyz_proto_depIdxs = nil
}
