// Resik
// Author: Dedy Fajar Setyawan
// See: https://github.com/dedyf5/resik

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        v4.25.1
// source: app/grpc/proto/meta/meta.proto

package meta

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Meta struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Total uint64    `protobuf:"varint,1,opt,name=Total,proto3" json:"total" example:"100"`  
	Limit int32     `protobuf:"varint,2,opt,name=Limit,proto3" json:"limit" example:"10"`  
	Page  *MetaPage `protobuf:"bytes,3,opt,name=Page,proto3" json:"page"`     
}

func (x *Meta) Reset() {
	*x = Meta{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_grpc_proto_meta_meta_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Meta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Meta) ProtoMessage() {}

func (x *Meta) ProtoReflect() protoreflect.Message {
	mi := &file_app_grpc_proto_meta_meta_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Meta.ProtoReflect.Descriptor instead.
func (*Meta) Descriptor() ([]byte, []int) {
	return file_app_grpc_proto_meta_meta_proto_rawDescGZIP(), []int{0}
}

func (x *Meta) GetTotal() uint64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *Meta) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *Meta) GetPage() *MetaPage {
	if x != nil {
		return x.Page
	}
	return nil
}

type MetaPage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	First    int32  `protobuf:"varint,1,opt,name=First,proto3" json:"first" example:"1"`              
	Previous *int32 `protobuf:"varint,2,opt,name=Previous,proto3,oneof" json:"previous" example:"2"`  
	Current  int32  `protobuf:"varint,3,opt,name=Current,proto3" json:"current" example:"3"`          
	Next     *int32 `protobuf:"varint,4,opt,name=Next,proto3,oneof" json:"next" example:"4"`          
	Last     int32  `protobuf:"varint,5,opt,name=Last,proto3" json:"last" example:"9"`                
}

func (x *MetaPage) Reset() {
	*x = MetaPage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_grpc_proto_meta_meta_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MetaPage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetaPage) ProtoMessage() {}

func (x *MetaPage) ProtoReflect() protoreflect.Message {
	mi := &file_app_grpc_proto_meta_meta_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetaPage.ProtoReflect.Descriptor instead.
func (*MetaPage) Descriptor() ([]byte, []int) {
	return file_app_grpc_proto_meta_meta_proto_rawDescGZIP(), []int{1}
}

func (x *MetaPage) GetFirst() int32 {
	if x != nil {
		return x.First
	}
	return 0
}

func (x *MetaPage) GetPrevious() int32 {
	if x != nil && x.Previous != nil {
		return *x.Previous
	}
	return 0
}

func (x *MetaPage) GetCurrent() int32 {
	if x != nil {
		return x.Current
	}
	return 0
}

func (x *MetaPage) GetNext() int32 {
	if x != nil && x.Next != nil {
		return *x.Next
	}
	return 0
}

func (x *MetaPage) GetLast() int32 {
	if x != nil {
		return x.Last
	}
	return 0
}

var File_app_grpc_proto_meta_meta_proto protoreflect.FileDescriptor

var file_app_grpc_proto_meta_meta_proto_rawDesc = []byte{
	0x0a, 0x1e, 0x61, 0x70, 0x70, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2f, 0x6d, 0x65, 0x74, 0x61, 0x2f, 0x6d, 0x65, 0x74, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x04, 0x6d, 0x65, 0x74, 0x61, 0x22, 0x56, 0x0a, 0x04, 0x4d, 0x65, 0x74, 0x61, 0x12, 0x14,
	0x0a, 0x05, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x54,
	0x6f, 0x74, 0x61, 0x6c, 0x12, 0x14, 0x0a, 0x05, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x05, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x12, 0x22, 0x0a, 0x04, 0x50, 0x61,
	0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x6d, 0x65, 0x74, 0x61, 0x2e,
	0x4d, 0x65, 0x74, 0x61, 0x50, 0x61, 0x67, 0x65, 0x52, 0x04, 0x50, 0x61, 0x67, 0x65, 0x22, 0x9e,
	0x01, 0x0a, 0x08, 0x4d, 0x65, 0x74, 0x61, 0x50, 0x61, 0x67, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x46,
	0x69, 0x72, 0x73, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x46, 0x69, 0x72, 0x73,
	0x74, 0x12, 0x1f, 0x0a, 0x08, 0x50, 0x72, 0x65, 0x76, 0x69, 0x6f, 0x75, 0x73, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x05, 0x48, 0x00, 0x52, 0x08, 0x50, 0x72, 0x65, 0x76, 0x69, 0x6f, 0x75, 0x73, 0x88,
	0x01, 0x01, 0x12, 0x18, 0x0a, 0x07, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x07, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x12, 0x17, 0x0a, 0x04,
	0x4e, 0x65, 0x78, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x48, 0x01, 0x52, 0x04, 0x4e, 0x65,
	0x78, 0x74, 0x88, 0x01, 0x01, 0x12, 0x12, 0x0a, 0x04, 0x4c, 0x61, 0x73, 0x74, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x04, 0x4c, 0x61, 0x73, 0x74, 0x42, 0x0b, 0x0a, 0x09, 0x5f, 0x50, 0x72,
	0x65, 0x76, 0x69, 0x6f, 0x75, 0x73, 0x42, 0x07, 0x0a, 0x05, 0x5f, 0x4e, 0x65, 0x78, 0x74, 0x42,
	0x2d, 0x5a, 0x2b, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x64, 0x65,
	0x64, 0x79, 0x66, 0x35, 0x2f, 0x72, 0x65, 0x73, 0x69, 0x6b, 0x2f, 0x61, 0x70, 0x70, 0x2f, 0x67,
	0x72, 0x70, 0x63, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6d, 0x65, 0x74, 0x61, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_app_grpc_proto_meta_meta_proto_rawDescOnce sync.Once
	file_app_grpc_proto_meta_meta_proto_rawDescData = file_app_grpc_proto_meta_meta_proto_rawDesc
)

func file_app_grpc_proto_meta_meta_proto_rawDescGZIP() []byte {
	file_app_grpc_proto_meta_meta_proto_rawDescOnce.Do(func() {
		file_app_grpc_proto_meta_meta_proto_rawDescData = protoimpl.X.CompressGZIP(file_app_grpc_proto_meta_meta_proto_rawDescData)
	})
	return file_app_grpc_proto_meta_meta_proto_rawDescData
}

var file_app_grpc_proto_meta_meta_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_app_grpc_proto_meta_meta_proto_goTypes = []interface{}{
	(*Meta)(nil),     // 0: meta.Meta
	(*MetaPage)(nil), // 1: meta.MetaPage
}
var file_app_grpc_proto_meta_meta_proto_depIdxs = []int32{
	1, // 0: meta.Meta.Page:type_name -> meta.MetaPage
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_app_grpc_proto_meta_meta_proto_init() }
func file_app_grpc_proto_meta_meta_proto_init() {
	if File_app_grpc_proto_meta_meta_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_app_grpc_proto_meta_meta_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Meta); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_grpc_proto_meta_meta_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MetaPage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_app_grpc_proto_meta_meta_proto_msgTypes[1].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_app_grpc_proto_meta_meta_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_app_grpc_proto_meta_meta_proto_goTypes,
		DependencyIndexes: file_app_grpc_proto_meta_meta_proto_depIdxs,
		MessageInfos:      file_app_grpc_proto_meta_meta_proto_msgTypes,
	}.Build()
	File_app_grpc_proto_meta_meta_proto = out.File
	file_app_grpc_proto_meta_meta_proto_rawDesc = nil
	file_app_grpc_proto_meta_meta_proto_goTypes = nil
	file_app_grpc_proto_meta_meta_proto_depIdxs = nil
}
