// Resik
// Author: Dedy Fajar Setyawan
// See: https://github.com/dedyf5/resik

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        v4.25.1
// source: app/grpc/handler/transaction/merchant.proto

package transaction

import (
	meta "github.com/dedyf5/resik/app/grpc/proto/meta"
	status "github.com/dedyf5/resik/app/grpc/proto/status"
	response "github.com/dedyf5/resik/core/transaction/response"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MerchantOmzetGetRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status *status.Status            `protobuf:"bytes,1,opt,name=Status,proto3" json:"status"`  
	Data   []*response.MerchantOmzet `protobuf:"bytes,2,rep,name=Data,proto3" json:"data"`      
	Meta   *meta.Meta                `protobuf:"bytes,3,opt,name=Meta,proto3" json:"meta"`      
}

func (x *MerchantOmzetGetRes) Reset() {
	*x = MerchantOmzetGetRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_grpc_handler_transaction_merchant_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MerchantOmzetGetRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MerchantOmzetGetRes) ProtoMessage() {}

func (x *MerchantOmzetGetRes) ProtoReflect() protoreflect.Message {
	mi := &file_app_grpc_handler_transaction_merchant_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MerchantOmzetGetRes.ProtoReflect.Descriptor instead.
func (*MerchantOmzetGetRes) Descriptor() ([]byte, []int) {
	return file_app_grpc_handler_transaction_merchant_proto_rawDescGZIP(), []int{0}
}

func (x *MerchantOmzetGetRes) GetStatus() *status.Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *MerchantOmzetGetRes) GetData() []*response.MerchantOmzet {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *MerchantOmzetGetRes) GetMeta() *meta.Meta {
	if x != nil {
		return x.Meta
	}
	return nil
}

var File_app_grpc_handler_transaction_merchant_proto protoreflect.FileDescriptor

var file_app_grpc_handler_transaction_merchant_proto_rawDesc = []byte{
	0x0a, 0x2b, 0x61, 0x70, 0x70, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x68, 0x61, 0x6e, 0x64, 0x6c,
	0x65, 0x72, 0x2f, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2f, 0x6d,
	0x65, 0x72, 0x63, 0x68, 0x61, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x74,
	0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x1a, 0x1e, 0x61, 0x70, 0x70, 0x2f,
	0x67, 0x72, 0x70, 0x63, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6d, 0x65, 0x74, 0x61, 0x2f,
	0x6d, 0x65, 0x74, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x22, 0x61, 0x70, 0x70, 0x2f,
	0x67, 0x72, 0x70, 0x63, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x2f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x28,
	0x63, 0x6f, 0x72, 0x65, 0x2f, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x2f, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2f, 0x6d, 0x65, 0x72, 0x63, 0x68, 0x61,
	0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x8a, 0x01, 0x0a, 0x13, 0x4d, 0x65, 0x72,
	0x63, 0x68, 0x61, 0x6e, 0x74, 0x4f, 0x6d, 0x7a, 0x65, 0x74, 0x47, 0x65, 0x74, 0x52, 0x65, 0x73,
	0x12, 0x26, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0e, 0x2e, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x52, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x2b, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61,
	0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x2e, 0x4d, 0x65, 0x72, 0x63, 0x68, 0x61, 0x6e, 0x74, 0x4f, 0x6d, 0x7a, 0x65, 0x74, 0x52,
	0x04, 0x44, 0x61, 0x74, 0x61, 0x12, 0x1e, 0x0a, 0x04, 0x4d, 0x65, 0x74, 0x61, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x6d, 0x65, 0x74, 0x61, 0x2e, 0x4d, 0x65, 0x74, 0x61, 0x52,
	0x04, 0x4d, 0x65, 0x74, 0x61, 0x42, 0x36, 0x5a, 0x34, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x64, 0x65, 0x64, 0x79, 0x66, 0x35, 0x2f, 0x72, 0x65, 0x73, 0x69, 0x6b,
	0x2f, 0x61, 0x70, 0x70, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x68, 0x61, 0x6e, 0x64, 0x6c, 0x65,
	0x72, 0x2f, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_app_grpc_handler_transaction_merchant_proto_rawDescOnce sync.Once
	file_app_grpc_handler_transaction_merchant_proto_rawDescData = file_app_grpc_handler_transaction_merchant_proto_rawDesc
)

func file_app_grpc_handler_transaction_merchant_proto_rawDescGZIP() []byte {
	file_app_grpc_handler_transaction_merchant_proto_rawDescOnce.Do(func() {
		file_app_grpc_handler_transaction_merchant_proto_rawDescData = protoimpl.X.CompressGZIP(file_app_grpc_handler_transaction_merchant_proto_rawDescData)
	})
	return file_app_grpc_handler_transaction_merchant_proto_rawDescData
}

var file_app_grpc_handler_transaction_merchant_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_app_grpc_handler_transaction_merchant_proto_goTypes = []interface{}{
	(*MerchantOmzetGetRes)(nil),    // 0: transaction.MerchantOmzetGetRes
	(*status.Status)(nil),          // 1: status.Status
	(*response.MerchantOmzet)(nil), // 2: response.MerchantOmzet
	(*meta.Meta)(nil),              // 3: meta.Meta
}
var file_app_grpc_handler_transaction_merchant_proto_depIdxs = []int32{
	1, // 0: transaction.MerchantOmzetGetRes.Status:type_name -> status.Status
	2, // 1: transaction.MerchantOmzetGetRes.Data:type_name -> response.MerchantOmzet
	3, // 2: transaction.MerchantOmzetGetRes.Meta:type_name -> meta.Meta
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_app_grpc_handler_transaction_merchant_proto_init() }
func file_app_grpc_handler_transaction_merchant_proto_init() {
	if File_app_grpc_handler_transaction_merchant_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_app_grpc_handler_transaction_merchant_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MerchantOmzetGetRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_app_grpc_handler_transaction_merchant_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_app_grpc_handler_transaction_merchant_proto_goTypes,
		DependencyIndexes: file_app_grpc_handler_transaction_merchant_proto_depIdxs,
		MessageInfos:      file_app_grpc_handler_transaction_merchant_proto_msgTypes,
	}.Build()
	File_app_grpc_handler_transaction_merchant_proto = out.File
	file_app_grpc_handler_transaction_merchant_proto_rawDesc = nil
	file_app_grpc_handler_transaction_merchant_proto_goTypes = nil
	file_app_grpc_handler_transaction_merchant_proto_depIdxs = nil
}
