// Resik
// Author: Dedy Fajar Setyawan
// See: https://github.com/dedyf5/resik

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        v4.25.1
// source: app/grpc/handler/transaction/outlet.proto

package transaction

import (
	meta "github.com/dedyf5/resik/app/grpc/proto/meta"
	status "github.com/dedyf5/resik/app/grpc/proto/status"
	res "github.com/dedyf5/resik/core/transaction/res"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OutletOmzetGetReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OutletID      uint64  `protobuf:"varint,1,opt,name=OutletID,proto3" json:"outlet_id" example:"1"`           
	Mode          string  `protobuf:"bytes,2,opt,name=Mode,proto3" json:"mode" example:"day"`                    
	DateTimeStart string  `protobuf:"bytes,3,opt,name=DateTimeStart,proto3" json:"datetime_start" example:"2023-11-22 13:45:00"`  
	DateTimeEnd   string  `protobuf:"bytes,4,opt,name=DateTimeEnd,proto3" json:"datetime_end" example:"2023-11-22 13:45:00"`      
	Search        string  `protobuf:"bytes,5,opt,name=Search,proto3" json:"search" example:"keyword"`                
	Order         *string `protobuf:"bytes,6,opt,name=Order,proto3,oneof" json:"order" example:"period"`            
	Page          *uint32 `protobuf:"varint,7,opt,name=Page,proto3,oneof" json:"page" example:"1"`             
	Limit         *uint32 `protobuf:"varint,8,opt,name=Limit,proto3,oneof" json:"limit" example:"10"`           
}

func (x *OutletOmzetGetReq) Reset() {
	*x = OutletOmzetGetReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_grpc_handler_transaction_outlet_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OutletOmzetGetReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OutletOmzetGetReq) ProtoMessage() {}

func (x *OutletOmzetGetReq) ProtoReflect() protoreflect.Message {
	mi := &file_app_grpc_handler_transaction_outlet_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OutletOmzetGetReq.ProtoReflect.Descriptor instead.
func (*OutletOmzetGetReq) Descriptor() ([]byte, []int) {
	return file_app_grpc_handler_transaction_outlet_proto_rawDescGZIP(), []int{0}
}

func (x *OutletOmzetGetReq) GetOutletID() uint64 {
	if x != nil {
		return x.OutletID
	}
	return 0
}

func (x *OutletOmzetGetReq) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *OutletOmzetGetReq) GetDateTimeStart() string {
	if x != nil {
		return x.DateTimeStart
	}
	return ""
}

func (x *OutletOmzetGetReq) GetDateTimeEnd() string {
	if x != nil {
		return x.DateTimeEnd
	}
	return ""
}

func (x *OutletOmzetGetReq) GetSearch() string {
	if x != nil {
		return x.Search
	}
	return ""
}

func (x *OutletOmzetGetReq) GetOrder() string {
	if x != nil && x.Order != nil {
		return *x.Order
	}
	return ""
}

func (x *OutletOmzetGetReq) GetPage() uint32 {
	if x != nil && x.Page != nil {
		return *x.Page
	}
	return 0
}

func (x *OutletOmzetGetReq) GetLimit() uint32 {
	if x != nil && x.Limit != nil {
		return *x.Limit
	}
	return 0
}

type OutletOmzetGetRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status *status.Status     `protobuf:"bytes,1,opt,name=Status,proto3" json:"status"`  
	Data   []*res.OutletOmzet `protobuf:"bytes,2,rep,name=Data,proto3" json:"data"`      
	Meta   *meta.Meta         `protobuf:"bytes,3,opt,name=Meta,proto3" json:"meta"`      
}

func (x *OutletOmzetGetRes) Reset() {
	*x = OutletOmzetGetRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_grpc_handler_transaction_outlet_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OutletOmzetGetRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OutletOmzetGetRes) ProtoMessage() {}

func (x *OutletOmzetGetRes) ProtoReflect() protoreflect.Message {
	mi := &file_app_grpc_handler_transaction_outlet_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OutletOmzetGetRes.ProtoReflect.Descriptor instead.
func (*OutletOmzetGetRes) Descriptor() ([]byte, []int) {
	return file_app_grpc_handler_transaction_outlet_proto_rawDescGZIP(), []int{1}
}

func (x *OutletOmzetGetRes) GetStatus() *status.Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *OutletOmzetGetRes) GetData() []*res.OutletOmzet {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *OutletOmzetGetRes) GetMeta() *meta.Meta {
	if x != nil {
		return x.Meta
	}
	return nil
}

var File_app_grpc_handler_transaction_outlet_proto protoreflect.FileDescriptor

var file_app_grpc_handler_transaction_outlet_proto_rawDesc = []byte{
	0x0a, 0x29, 0x61, 0x70, 0x70, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x68, 0x61, 0x6e, 0x64, 0x6c,
	0x65, 0x72, 0x2f, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2f, 0x6f,
	0x75, 0x74, 0x6c, 0x65, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x74, 0x72, 0x61,
	0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x1a, 0x1e, 0x61, 0x70, 0x70, 0x2f, 0x67, 0x72,
	0x70, 0x63, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6d, 0x65, 0x74, 0x61, 0x2f, 0x6d, 0x65,
	0x74, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x22, 0x61, 0x70, 0x70, 0x2f, 0x67, 0x72,
	0x70, 0x63, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x2f,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x21, 0x63, 0x6f,
	0x72, 0x65, 0x2f, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2f, 0x72,
	0x65, 0x73, 0x2f, 0x6f, 0x75, 0x74, 0x6c, 0x65, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x8f, 0x02, 0x0a, 0x11, 0x4f, 0x75, 0x74, 0x6c, 0x65, 0x74, 0x4f, 0x6d, 0x7a, 0x65, 0x74, 0x47,
	0x65, 0x74, 0x52, 0x65, 0x71, 0x12, 0x1a, 0x0a, 0x08, 0x4f, 0x75, 0x74, 0x6c, 0x65, 0x74, 0x49,
	0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x4f, 0x75, 0x74, 0x6c, 0x65, 0x74, 0x49,
	0x44, 0x12, 0x12, 0x0a, 0x04, 0x4d, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x4d, 0x6f, 0x64, 0x65, 0x12, 0x24, 0x0a, 0x0d, 0x44, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d,
	0x65, 0x53, 0x74, 0x61, 0x72, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x44, 0x61,
	0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x72, 0x74, 0x12, 0x20, 0x0a, 0x0b, 0x44,
	0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x45, 0x6e, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0b, 0x44, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x45, 0x6e, 0x64, 0x12, 0x16, 0x0a,
	0x06, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x53,
	0x65, 0x61, 0x72, 0x63, 0x68, 0x12, 0x19, 0x0a, 0x05, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x05, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x88, 0x01, 0x01,
	0x12, 0x17, 0x0a, 0x04, 0x50, 0x61, 0x67, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0d, 0x48, 0x01,
	0x52, 0x04, 0x50, 0x61, 0x67, 0x65, 0x88, 0x01, 0x01, 0x12, 0x19, 0x0a, 0x05, 0x4c, 0x69, 0x6d,
	0x69, 0x74, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0d, 0x48, 0x02, 0x52, 0x05, 0x4c, 0x69, 0x6d, 0x69,
	0x74, 0x88, 0x01, 0x01, 0x42, 0x08, 0x0a, 0x06, 0x5f, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x42, 0x07,
	0x0a, 0x05, 0x5f, 0x50, 0x61, 0x67, 0x65, 0x42, 0x08, 0x0a, 0x06, 0x5f, 0x4c, 0x69, 0x6d, 0x69,
	0x74, 0x22, 0x81, 0x01, 0x0a, 0x11, 0x4f, 0x75, 0x74, 0x6c, 0x65, 0x74, 0x4f, 0x6d, 0x7a, 0x65,
	0x74, 0x47, 0x65, 0x74, 0x52, 0x65, 0x73, 0x12, 0x26, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12,
	0x24, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e,
	0x72, 0x65, 0x73, 0x2e, 0x4f, 0x75, 0x74, 0x6c, 0x65, 0x74, 0x4f, 0x6d, 0x7a, 0x65, 0x74, 0x52,
	0x04, 0x44, 0x61, 0x74, 0x61, 0x12, 0x1e, 0x0a, 0x04, 0x4d, 0x65, 0x74, 0x61, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x6d, 0x65, 0x74, 0x61, 0x2e, 0x4d, 0x65, 0x74, 0x61, 0x52,
	0x04, 0x4d, 0x65, 0x74, 0x61, 0x42, 0x36, 0x5a, 0x34, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x64, 0x65, 0x64, 0x79, 0x66, 0x35, 0x2f, 0x72, 0x65, 0x73, 0x69, 0x6b,
	0x2f, 0x61, 0x70, 0x70, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x68, 0x61, 0x6e, 0x64, 0x6c, 0x65,
	0x72, 0x2f, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_app_grpc_handler_transaction_outlet_proto_rawDescOnce sync.Once
	file_app_grpc_handler_transaction_outlet_proto_rawDescData = file_app_grpc_handler_transaction_outlet_proto_rawDesc
)

func file_app_grpc_handler_transaction_outlet_proto_rawDescGZIP() []byte {
	file_app_grpc_handler_transaction_outlet_proto_rawDescOnce.Do(func() {
		file_app_grpc_handler_transaction_outlet_proto_rawDescData = protoimpl.X.CompressGZIP(file_app_grpc_handler_transaction_outlet_proto_rawDescData)
	})
	return file_app_grpc_handler_transaction_outlet_proto_rawDescData
}

var file_app_grpc_handler_transaction_outlet_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_app_grpc_handler_transaction_outlet_proto_goTypes = []interface{}{
	(*OutletOmzetGetReq)(nil), // 0: transaction.OutletOmzetGetReq
	(*OutletOmzetGetRes)(nil), // 1: transaction.OutletOmzetGetRes
	(*status.Status)(nil),     // 2: status.Status
	(*res.OutletOmzet)(nil),   // 3: res.OutletOmzet
	(*meta.Meta)(nil),         // 4: meta.Meta
}
var file_app_grpc_handler_transaction_outlet_proto_depIdxs = []int32{
	2, // 0: transaction.OutletOmzetGetRes.Status:type_name -> status.Status
	3, // 1: transaction.OutletOmzetGetRes.Data:type_name -> res.OutletOmzet
	4, // 2: transaction.OutletOmzetGetRes.Meta:type_name -> meta.Meta
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_app_grpc_handler_transaction_outlet_proto_init() }
func file_app_grpc_handler_transaction_outlet_proto_init() {
	if File_app_grpc_handler_transaction_outlet_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_app_grpc_handler_transaction_outlet_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OutletOmzetGetReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_grpc_handler_transaction_outlet_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OutletOmzetGetRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_app_grpc_handler_transaction_outlet_proto_msgTypes[0].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_app_grpc_handler_transaction_outlet_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_app_grpc_handler_transaction_outlet_proto_goTypes,
		DependencyIndexes: file_app_grpc_handler_transaction_outlet_proto_depIdxs,
		MessageInfos:      file_app_grpc_handler_transaction_outlet_proto_msgTypes,
	}.Build()
	File_app_grpc_handler_transaction_outlet_proto = out.File
	file_app_grpc_handler_transaction_outlet_proto_rawDesc = nil
	file_app_grpc_handler_transaction_outlet_proto_goTypes = nil
	file_app_grpc_handler_transaction_outlet_proto_depIdxs = nil
}
