definitions:
  response.MerchantOmzet:
    properties:
      merchant_name:
        example: Resik Merchant
        type: string
      omzet:
        example: 1.0000005e+06
        type: number
      period:
        example: "2024-02-06"
        type: string
    type: object
  response.Response:
    properties:
      data: {}
      meta:
        $ref: '#/definitions/response.ResponseMeta'
      status:
        $ref: '#/definitions/response.ResponseStatus'
    type: object
  response.ResponseMeta:
    properties:
      limit:
        example: 10
        type: integer
      page:
        $ref: '#/definitions/response.ResponsePage'
      total:
        example: 100
        type: integer
    type: object
  response.ResponsePage:
    properties:
      current:
        example: 3
        type: integer
      first:
        example: 1
        type: integer
      last:
        example: 9
        type: integer
      next:
        example: 4
        type: integer
      previous:
        example: 2
        type: integer
    type: object
  response.ResponseStatus:
    properties:
      code:
        example: "200.1"
        type: string
      detail:
        additionalProperties:
          type: string
        type: object
      message:
        example: OK
        type: string
    type: object
info:
  contact: {}
paths:
  /transaction/merchant/{id}/omzet:
    get:
      consumes:
      - application/json
      description: Get merchant omzet by merchant id
      parameters:
      - description: Merchant ID
        in: path
        name: id
        required: true
        type: integer
      - example: "2024-02-01 13:45:00"
        in: query
        name: datetime_end
        required: true
        type: string
      - example: "2024-02-01 13:45:00"
        in: query
        name: datetime_start
        required: true
        type: string
      - enum:
        - en
        - id
        in: query
        name: lang
        type: string
      - example: 10
        in: query
        maximum: 100
        minimum: 1
        name: limit
        type: integer
      - enum:
        - day
        - month
        - year
        example: day
        in: query
        name: mode
        required: true
        type: string
      - example: period
        in: query
        name: order
        type: string
      - example: 1
        in: query
        minimum: 1
        name: page
        type: integer
      - example: keyword
        in: query
        name: search
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/response.MerchantOmzet'
                  type: array
              type: object
        "400":
          description: Bad Request
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                data:
                  type: object
              type: object
        "500":
          description: Internal Server Error
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                data:
                  type: object
              type: object
      summary: Get Merchant Omzet
      tags:
      - transaction
swagger: "2.0"
