// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplatehttp = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/transaction/merchant/{id}/omzet": {
            "get": {
                "description": "Get merchant omzet by merchant id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "transaction"
                ],
                "summary": "Get Merchant Omzet",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Merchant ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "example": "2024-02-01 13:45:00",
                        "name": "datetime_end",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "example": "2024-02-01 13:45:00",
                        "name": "datetime_start",
                        "in": "query",
                        "required": true
                    },
                    {
                        "maximum": 100,
                        "minimum": 1,
                        "type": "integer",
                        "example": 10,
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "day",
                            "month",
                            "year"
                        ],
                        "type": "string",
                        "example": "day",
                        "name": "mode",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "example": "period",
                        "name": "order",
                        "in": "query"
                    },
                    {
                        "minimum": 1,
                        "type": "integer",
                        "example": 1,
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "example": "keyword",
                        "name": "search",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/response.MerchantOmzet"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "response.MerchantOmzet": {
            "type": "object",
            "properties": {
                "merchant_name": {
                    "type": "string",
                    "example": "Resik Merchant"
                },
                "omzet": {
                    "type": "number",
                    "example": 1000000.5
                },
                "period": {
                    "type": "string",
                    "example": "2024-02-06"
                }
            }
        },
        "response.Response": {
            "type": "object",
            "properties": {
                "data": {},
                "meta": {
                    "$ref": "#/definitions/response.ResponseMeta"
                },
                "status": {
                    "$ref": "#/definitions/response.ResponseStatus"
                }
            }
        },
        "response.ResponseMeta": {
            "type": "object",
            "properties": {
                "limit": {
                    "type": "integer",
                    "example": 10
                },
                "page": {
                    "$ref": "#/definitions/response.ResponsePage"
                },
                "total": {
                    "type": "integer",
                    "example": 100
                }
            }
        },
        "response.ResponsePage": {
            "type": "object",
            "properties": {
                "current": {
                    "type": "integer",
                    "example": 3
                },
                "first": {
                    "type": "integer",
                    "example": 1
                },
                "last": {
                    "type": "integer",
                    "example": 9
                },
                "next": {
                    "type": "integer",
                    "example": 4
                },
                "previous": {
                    "type": "integer",
                    "example": 2
                }
            }
        },
        "response.ResponseStatus": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string",
                    "example": "200.1"
                },
                "detail": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "message": {
                    "type": "string",
                    "example": "OK"
                }
            }
        }
    }
}`

// SwaggerInfohttp holds exported Swagger Info so clients can modify it
var SwaggerInfohttp = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "http",
	SwaggerTemplate:  docTemplatehttp,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfohttp.InstanceName(), SwaggerInfohttp)
}
