// Resik
// Author: Dedy Fajar Setyawan
// See: https://github.com/dedyf5/resik

syntax = "proto3";

package general;
option go_package = "github.com/dedyf5/resik/app/grpc/handler/general";

import "core/common/lang.proto";
import "core/common/status.proto";
import "core/app/response/app.proto";

message HomeReq {
    core.common.Lang lang = 1; // @gotags: json:"lang"
}

message HomeRes {
    core.common.Status status = 1; // @gotags: json:"status"
    core.app.response.App data = 2; // @gotags: json:"data"
}
