// Resik
// Author: Dedy Fajar Setyawan
// See: https://github.com/dedyf5/resik

syntax = "proto3";

package response;
option go_package = "github.com/dedyf5/resik/core/transaction/response";

import "core/transaction/response/common.proto";

// Message response for branch omzet transaction.
message BranchOmzet {
    Branch branch = 1; // @gotags: json:"branch"
    double omzet = 2; // @gotags: json:"omzet" example:"5000.5"
    string period = 3; // @gotags: json:"period" example:"2023-11-22"
}
