// Resik
// Author: Dedy Fajar Setyawan
// See: https://github.com/dedyf5/resik

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v4.25.1
// source: core/transaction/response/list.proto

package response

import (
	common "github.com/dedyf5/resik/core/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Message response item for transactions list
type TransactionList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id           string         `protobuf:"bytes,1,opt,name=id,proto3" json:"id" example:"01a0eca283a4796fa0e51d3ab1cfd2ba"`                                          
	Branch       *common.Branch `protobuf:"bytes,2,opt,name=branch,proto3" json:"branch"`                                  
	BillTotal    float64        `protobuf:"fixed64,3,opt,name=bill_total,json=billTotal,proto3" json:"bill_total" example:"1000.5"`         
	TransactedAt string         `protobuf:"bytes,4,opt,name=transacted_at,json=transactedAt,proto3" json:"transacted_at" example:"2024-02-02T19:52:41Z"`  
	Creator      *common.User   `protobuf:"bytes,5,opt,name=creator,proto3" json:"creator"`                                
	Updater      *common.User   `protobuf:"bytes,6,opt,name=updater,proto3" json:"updater"`                                
}

func (x *TransactionList) Reset() {
	*x = TransactionList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_core_transaction_response_list_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TransactionList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionList) ProtoMessage() {}

func (x *TransactionList) ProtoReflect() protoreflect.Message {
	mi := &file_core_transaction_response_list_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionList.ProtoReflect.Descriptor instead.
func (*TransactionList) Descriptor() ([]byte, []int) {
	return file_core_transaction_response_list_proto_rawDescGZIP(), []int{0}
}

func (x *TransactionList) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TransactionList) GetBranch() *common.Branch {
	if x != nil {
		return x.Branch
	}
	return nil
}

func (x *TransactionList) GetBillTotal() float64 {
	if x != nil {
		return x.BillTotal
	}
	return 0
}

func (x *TransactionList) GetTransactedAt() string {
	if x != nil {
		return x.TransactedAt
	}
	return ""
}

func (x *TransactionList) GetCreator() *common.User {
	if x != nil {
		return x.Creator
	}
	return nil
}

func (x *TransactionList) GetUpdater() *common.User {
	if x != nil {
		return x.Updater
	}
	return nil
}

var File_core_transaction_response_list_proto protoreflect.FileDescriptor

var file_core_transaction_response_list_proto_rawDesc = []byte{
	0x0a, 0x24, 0x63, 0x6f, 0x72, 0x65, 0x2f, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x2f, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2f, 0x6c, 0x69, 0x73, 0x74,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x19, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x74, 0x72, 0x61,
	0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x1a, 0x16, 0x63, 0x6f, 0x72, 0x65, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x75,
	0x73, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1e, 0x63, 0x6f, 0x72, 0x65, 0x2f,
	0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x6f, 0x72, 0x67, 0x61, 0x6e, 0x69, 0x7a, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xec, 0x01, 0x0a, 0x0f, 0x54, 0x72,
	0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x2b, 0x0a,
	0x06, 0x62, 0x72, 0x61, 0x6e, 0x63, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e,
	0x63, 0x6f, 0x72, 0x65, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x42, 0x72, 0x61, 0x6e,
	0x63, 0x68, 0x52, 0x06, 0x62, 0x72, 0x61, 0x6e, 0x63, 0x68, 0x12, 0x1d, 0x0a, 0x0a, 0x62, 0x69,
	0x6c, 0x6c, 0x5f, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x52, 0x09,
	0x62, 0x69, 0x6c, 0x6c, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x12, 0x23, 0x0a, 0x0d, 0x74, 0x72, 0x61,
	0x6e, 0x73, 0x61, 0x63, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0c, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x2b,
	0x0a, 0x07, 0x63, 0x72, 0x65, 0x61, 0x74, 0x6f, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x11, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x55, 0x73,
	0x65, 0x72, 0x52, 0x07, 0x63, 0x72, 0x65, 0x61, 0x74, 0x6f, 0x72, 0x12, 0x2b, 0x0a, 0x07, 0x75,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x72, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x63,
	0x6f, 0x72, 0x65, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x52,
	0x07, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x72, 0x42, 0x33, 0x5a, 0x31, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x64, 0x65, 0x64, 0x79, 0x66, 0x35, 0x2f, 0x72, 0x65,
	0x73, 0x69, 0x6b, 0x2f, 0x63, 0x6f, 0x72, 0x65, 0x2f, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x2f, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_core_transaction_response_list_proto_rawDescOnce sync.Once
	file_core_transaction_response_list_proto_rawDescData = file_core_transaction_response_list_proto_rawDesc
)

func file_core_transaction_response_list_proto_rawDescGZIP() []byte {
	file_core_transaction_response_list_proto_rawDescOnce.Do(func() {
		file_core_transaction_response_list_proto_rawDescData = protoimpl.X.CompressGZIP(file_core_transaction_response_list_proto_rawDescData)
	})
	return file_core_transaction_response_list_proto_rawDescData
}

var file_core_transaction_response_list_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_core_transaction_response_list_proto_goTypes = []any{
	(*TransactionList)(nil), // 0: core.transaction.response.TransactionList
	(*common.Branch)(nil),   // 1: core.common.Branch
	(*common.User)(nil),     // 2: core.common.User
}
var file_core_transaction_response_list_proto_depIdxs = []int32{
	1, // 0: core.transaction.response.TransactionList.branch:type_name -> core.common.Branch
	2, // 1: core.transaction.response.TransactionList.creator:type_name -> core.common.User
	2, // 2: core.transaction.response.TransactionList.updater:type_name -> core.common.User
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_core_transaction_response_list_proto_init() }
func file_core_transaction_response_list_proto_init() {
	if File_core_transaction_response_list_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_core_transaction_response_list_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*TransactionList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_core_transaction_response_list_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_core_transaction_response_list_proto_goTypes,
		DependencyIndexes: file_core_transaction_response_list_proto_depIdxs,
		MessageInfos:      file_core_transaction_response_list_proto_msgTypes,
	}.Build()
	File_core_transaction_response_list_proto = out.File
	file_core_transaction_response_list_proto_rawDesc = nil
	file_core_transaction_response_list_proto_goTypes = nil
	file_core_transaction_response_list_proto_depIdxs = nil
}
