// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package bootstrap

import (
	"context"
	"github.com/dedyf5/resik/app/grpc/handler/general"
	"github.com/dedyf5/resik/app/grpc/handler/health"
	merchant2 "github.com/dedyf5/resik/app/grpc/handler/merchant"
	transaction2 "github.com/dedyf5/resik/app/grpc/handler/transaction"
	user2 "github.com/dedyf5/resik/app/grpc/handler/user"
	"github.com/dedyf5/resik/app/grpc/middleware"
	"github.com/dedyf5/resik/config"
	health2 "github.com/dedyf5/resik/core/health"
	service4 "github.com/dedyf5/resik/core/health/service"
	merchant3 "github.com/dedyf5/resik/core/merchant"
	"github.com/dedyf5/resik/core/merchant/service"
	transaction3 "github.com/dedyf5/resik/core/transaction"
	service2 "github.com/dedyf5/resik/core/transaction/service"
	user3 "github.com/dedyf5/resik/core/user"
	service3 "github.com/dedyf5/resik/core/user/service"
	"github.com/dedyf5/resik/ctx/log"
	"github.com/dedyf5/resik/drivers"
	config2 "github.com/dedyf5/resik/entities/config"
	"github.com/dedyf5/resik/pkg/hash"
	"github.com/dedyf5/resik/repositories"
	"github.com/dedyf5/resik/repositories/check"
	"github.com/dedyf5/resik/repositories/merchant"
	"github.com/dedyf5/resik/repositories/transaction"
	"github.com/dedyf5/resik/repositories/user"
	"github.com/dedyf5/resik/utils/ratelimit"
	"github.com/dedyf5/resik/utils/validator"
	"github.com/google/wire"
)

// Injectors from wire.go:

func InitializeHTTP(c context.Context) (*App, func(), error) {
	config := _wireConfigValue
	configLog := config.Log
	module := config.Module
	logLog := log.Get(configLog, module)
	generalHandler := general.New(config, logLog)
	tag := module.LangDefault
	validate := validator.New(tag)
	sqlConfig := config.Database
	sqlEngine := sqlConfig.Engine
	bool2 := _wireBoolValue
	db, cleanup, err := drivers.NewMySQLConnection(sqlConfig, bool2)
	if err != nil {
		return nil, nil, err
	}
	gormDB, cleanup2, err := drivers.NewGorm(sqlEngine, db, sqlConfig)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	merchantRepo := merchant.New(gormDB)
	serviceService := service.New(merchantRepo, config)
	merchantHandler := merchant2.New(logLog, validate, serviceService)
	transactionRepo := transaction.New(gormDB)
	service5 := service2.New(transactionRepo, config)
	transactionHandler := transaction2.New(config, logLog, validate, service5)
	userRepo := user.New(gormDB)
	auth := config.Auth
	argon2Config := provideHasherConfig(auth)
	iHash := hash.NewArgon2Hasher(argon2Config)
	service6 := service3.New(userRepo, iHash, config)
	userHandler := user2.New(logLog, validate, service6)
	checkDatabaseRepo := check.NewCheckDatabaseRepo(db, config)
	redisConfig := config.Redis
	client, cleanup3, err := drivers.NewRedisConnection(redisConfig)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	checkRedisRepo := check.NewCheckRedisRepo(client, config)
	v := provideCheckerSlice(checkDatabaseRepo, checkRedisRepo)
	service7 := service4.New(v)
	healthHandler := health.New(service7)
	router := newRouter(config, generalHandler, merchantHandler, transactionHandler, userHandler, healthHandler)
	app := config.App
	rateLimit := config.RateLimit
	limiter, err := ratelimit.NewRateLimiter(app, rateLimit, client)
	if err != nil {
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	interceptor := middleware.NewInterceptor(module, auth, limiter, logLog)
	serverHTTP := newServerHTTP(c, config, router, interceptor)
	bootstrapApp, cleanup4, err := newApp(serverHTTP)
	if err != nil {
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	return bootstrapApp, func() {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
	}, nil
}

var (
	_wireConfigValue = *configGeneral
	_wireBoolValue   = false
)

// wire.go:

var configGeneral = config.Load(config2.ModuleTypeGRPC)

var configGeneralSet = wire.NewSet(wire.Value(*configGeneral), wire.FieldsOf(new(config.Config), "App", "Module", "HTTP", "Database", "Redis", "RateLimit", "Auth", "Log"), wire.FieldsOf(new(config2.Module), "Env", "LangDefault", "Type"), wire.FieldsOf(new(drivers.SQLConfig), "Engine"))

var utilSet = wire.NewSet(validator.New, ratelimit.NewRateLimiter, log.Get)

var interceptorSet = wire.NewSet(middleware.NewInterceptor)

var connSet = wire.NewSet(wire.Value(false), drivers.NewMySQLConnection, drivers.NewGorm, drivers.NewRedisConnection)

var repoSet = wire.NewSet(check.NewCheckDatabaseRepo, check.NewCheckRedisRepo, merchant.New, transaction.New, user.New, wire.Bind(new(repositories.ICheck), new(*check.CheckDatabaseRepo)), wire.Bind(new(repositories.IMerchant), new(*merchant.MerchantRepo)), wire.Bind(new(repositories.ITransaction), new(*transaction.TransactionRepo)), wire.Bind(new(repositories.IUser), new(*user.UserRepo)))

func provideHasherConfig(conf config2.Auth) *hash.Argon2Config {
	return &hash.Argon2Config{
		Memory:     conf.HashMemory,
		Iterations: conf.HashIterations,
	}
}

func provideCheckerSlice(db *check.CheckDatabaseRepo, redis *check.CheckRedisRepo) []repositories.ICheck {
	return []repositories.ICheck{db, redis}
}

var providerSet = wire.NewSet(
	provideHasherConfig, hash.NewArgon2Hasher, provideCheckerSlice,
)

var serviceSet = wire.NewSet(service4.New, service.New, service2.New, service3.New, wire.Bind(new(health2.IService), new(*service4.Service)), wire.Bind(new(merchant3.IService), new(*service.Service)), wire.Bind(new(transaction3.IService), new(*service2.Service)), wire.Bind(new(user3.IService), new(*service3.Service)))

var handlerSet = wire.NewSet(general.New, merchant2.New, transaction2.New, user2.New, health.New)
