// Code generated by MockGen. DO NOT EDIT.
// Source: repository.go
//
// Generated by this command:
//
//	mockgen -source repository.go -package mock -destination ./mock/repository.go
//

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	ctx "github.com/dedyf5/resik/ctx"
	check "github.com/dedyf5/resik/entities/check"
	merchant "github.com/dedyf5/resik/entities/merchant"
	param "github.com/dedyf5/resik/entities/merchant/param"
	outlet "github.com/dedyf5/resik/entities/outlet"
	transaction "github.com/dedyf5/resik/entities/transaction"
	param0 "github.com/dedyf5/resik/entities/transaction/param"
	user "github.com/dedyf5/resik/entities/user"
	response "github.com/dedyf5/resik/pkg/response"
	gomock "go.uber.org/mock/gomock"
)

// MockICheck is a mock of ICheck interface.
type MockICheck struct {
	ctrl     *gomock.Controller
	recorder *MockICheckMockRecorder
	isgomock struct{}
}

// MockICheckMockRecorder is the mock recorder for MockICheck.
type MockICheckMockRecorder struct {
	mock *MockICheck
}

// NewMockICheck creates a new mock instance.
func NewMockICheck(ctrl *gomock.Controller) *MockICheck {
	mock := &MockICheck{ctrl: ctrl}
	mock.recorder = &MockICheckMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockICheck) EXPECT() *MockICheckMockRecorder {
	return m.recorder
}

// Check mocks base method.
func (m *MockICheck) Check() check.CheckDetail {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Check")
	ret0, _ := ret[0].(check.CheckDetail)
	return ret0
}

// Check indicates an expected call of Check.
func (mr *MockICheckMockRecorder) Check() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Check", reflect.TypeOf((*MockICheck)(nil).Check))
}

// MockITransaction is a mock of ITransaction interface.
type MockITransaction struct {
	ctrl     *gomock.Controller
	recorder *MockITransactionMockRecorder
	isgomock struct{}
}

// MockITransactionMockRecorder is the mock recorder for MockITransaction.
type MockITransactionMockRecorder struct {
	mock *MockITransaction
}

// NewMockITransaction creates a new mock instance.
func NewMockITransaction(ctrl *gomock.Controller) *MockITransaction {
	mock := &MockITransaction{ctrl: ctrl}
	mock.recorder = &MockITransactionMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockITransaction) EXPECT() *MockITransactionMockRecorder {
	return m.recorder
}

// MerchantOmzetGetData mocks base method.
func (m *MockITransaction) MerchantOmzetGetData(arg0 *param0.MerchantOmzetGet) ([]transaction.MerchantOmzet, *response.Status) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MerchantOmzetGetData", arg0)
	ret0, _ := ret[0].([]transaction.MerchantOmzet)
	ret1, _ := ret[1].(*response.Status)
	return ret0, ret1
}

// MerchantOmzetGetData indicates an expected call of MerchantOmzetGetData.
func (mr *MockITransactionMockRecorder) MerchantOmzetGetData(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MerchantOmzetGetData", reflect.TypeOf((*MockITransaction)(nil).MerchantOmzetGetData), arg0)
}

// MerchantOmzetGetTotal mocks base method.
func (m *MockITransaction) MerchantOmzetGetTotal(arg0 *param0.MerchantOmzetGet) (int64, *response.Status) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MerchantOmzetGetTotal", arg0)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(*response.Status)
	return ret0, ret1
}

// MerchantOmzetGetTotal indicates an expected call of MerchantOmzetGetTotal.
func (mr *MockITransactionMockRecorder) MerchantOmzetGetTotal(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MerchantOmzetGetTotal", reflect.TypeOf((*MockITransaction)(nil).MerchantOmzetGetTotal), arg0)
}

// OutletOmzetGetData mocks base method.
func (m *MockITransaction) OutletOmzetGetData(arg0 *param0.OutletOmzetGet) ([]transaction.OutletOmzet, *response.Status) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OutletOmzetGetData", arg0)
	ret0, _ := ret[0].([]transaction.OutletOmzet)
	ret1, _ := ret[1].(*response.Status)
	return ret0, ret1
}

// OutletOmzetGetData indicates an expected call of OutletOmzetGetData.
func (mr *MockITransactionMockRecorder) OutletOmzetGetData(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OutletOmzetGetData", reflect.TypeOf((*MockITransaction)(nil).OutletOmzetGetData), arg0)
}

// OutletOmzetGetTotal mocks base method.
func (m *MockITransaction) OutletOmzetGetTotal(arg0 *param0.OutletOmzetGet) (int64, *response.Status) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OutletOmzetGetTotal", arg0)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(*response.Status)
	return ret0, ret1
}

// OutletOmzetGetTotal indicates an expected call of OutletOmzetGetTotal.
func (mr *MockITransactionMockRecorder) OutletOmzetGetTotal(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OutletOmzetGetTotal", reflect.TypeOf((*MockITransaction)(nil).OutletOmzetGetTotal), arg0)
}

// MockIUser is a mock of IUser interface.
type MockIUser struct {
	ctrl     *gomock.Controller
	recorder *MockIUserMockRecorder
	isgomock struct{}
}

// MockIUserMockRecorder is the mock recorder for MockIUser.
type MockIUserMockRecorder struct {
	mock *MockIUser
}

// NewMockIUser creates a new mock instance.
func NewMockIUser(ctrl *gomock.Controller) *MockIUser {
	mock := &MockIUser{ctrl: ctrl}
	mock.recorder = &MockIUserMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIUser) EXPECT() *MockIUserMockRecorder {
	return m.recorder
}

// MerchantIDsByUserIDGetData mocks base method.
func (m *MockIUser) MerchantIDsByUserIDGetData(userID uint64) ([]uint64, *response.Status) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MerchantIDsByUserIDGetData", userID)
	ret0, _ := ret[0].([]uint64)
	ret1, _ := ret[1].(*response.Status)
	return ret0, ret1
}

// MerchantIDsByUserIDGetData indicates an expected call of MerchantIDsByUserIDGetData.
func (mr *MockIUserMockRecorder) MerchantIDsByUserIDGetData(userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MerchantIDsByUserIDGetData", reflect.TypeOf((*MockIUser)(nil).MerchantIDsByUserIDGetData), userID)
}

// OutletMerchantByUserIDGetData mocks base method.
func (m *MockIUser) OutletMerchantByUserIDGetData(userID uint64) ([]outlet.Outlet, *response.Status) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OutletMerchantByUserIDGetData", userID)
	ret0, _ := ret[0].([]outlet.Outlet)
	ret1, _ := ret[1].(*response.Status)
	return ret0, ret1
}

// OutletMerchantByUserIDGetData indicates an expected call of OutletMerchantByUserIDGetData.
func (mr *MockIUserMockRecorder) OutletMerchantByUserIDGetData(userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OutletMerchantByUserIDGetData", reflect.TypeOf((*MockIUser)(nil).OutletMerchantByUserIDGetData), userID)
}

// UserByID mocks base method.
func (m *MockIUser) UserByID(arg0 *ctx.Ctx, userID uint64) (*user.User, *response.Status) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UserByID", arg0, userID)
	ret0, _ := ret[0].(*user.User)
	ret1, _ := ret[1].(*response.Status)
	return ret0, ret1
}

// UserByID indicates an expected call of UserByID.
func (mr *MockIUserMockRecorder) UserByID(arg0, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UserByID", reflect.TypeOf((*MockIUser)(nil).UserByID), arg0, userID)
}

// UserByUsername mocks base method.
func (m *MockIUser) UserByUsername(arg0 *ctx.Ctx, username string) (*user.User, *response.Status) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UserByUsername", arg0, username)
	ret0, _ := ret[0].(*user.User)
	ret1, _ := ret[1].(*response.Status)
	return ret0, ret1
}

// UserByUsername indicates an expected call of UserByUsername.
func (mr *MockIUserMockRecorder) UserByUsername(arg0, username any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UserByUsername", reflect.TypeOf((*MockIUser)(nil).UserByUsername), arg0, username)
}

// MockIMerchant is a mock of IMerchant interface.
type MockIMerchant struct {
	ctrl     *gomock.Controller
	recorder *MockIMerchantMockRecorder
	isgomock struct{}
}

// MockIMerchantMockRecorder is the mock recorder for MockIMerchant.
type MockIMerchantMockRecorder struct {
	mock *MockIMerchant
}

// NewMockIMerchant creates a new mock instance.
func NewMockIMerchant(ctrl *gomock.Controller) *MockIMerchant {
	mock := &MockIMerchant{ctrl: ctrl}
	mock.recorder = &MockIMerchantMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIMerchant) EXPECT() *MockIMerchantMockRecorder {
	return m.recorder
}

// MerchantDelete mocks base method.
func (m *MockIMerchant) MerchantDelete(c *ctx.Ctx, arg1 *merchant.Merchant) (bool, *response.Status) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MerchantDelete", c, arg1)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(*response.Status)
	return ret0, ret1
}

// MerchantDelete indicates an expected call of MerchantDelete.
func (mr *MockIMerchantMockRecorder) MerchantDelete(c, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MerchantDelete", reflect.TypeOf((*MockIMerchant)(nil).MerchantDelete), c, arg1)
}

// MerchantGetByIDAndUserID mocks base method.
func (m *MockIMerchant) MerchantGetByIDAndUserID(arg0 *ctx.Ctx, merchantID, userID uint64) (*merchant.Merchant, *response.Status) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MerchantGetByIDAndUserID", arg0, merchantID, userID)
	ret0, _ := ret[0].(*merchant.Merchant)
	ret1, _ := ret[1].(*response.Status)
	return ret0, ret1
}

// MerchantGetByIDAndUserID indicates an expected call of MerchantGetByIDAndUserID.
func (mr *MockIMerchantMockRecorder) MerchantGetByIDAndUserID(arg0, merchantID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MerchantGetByIDAndUserID", reflect.TypeOf((*MockIMerchant)(nil).MerchantGetByIDAndUserID), arg0, merchantID, userID)
}

// MerchantInsert mocks base method.
func (m *MockIMerchant) MerchantInsert(arg0 *ctx.Ctx, arg1 *merchant.Merchant) (bool, *response.Status) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MerchantInsert", arg0, arg1)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(*response.Status)
	return ret0, ret1
}

// MerchantInsert indicates an expected call of MerchantInsert.
func (mr *MockIMerchantMockRecorder) MerchantInsert(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MerchantInsert", reflect.TypeOf((*MockIMerchant)(nil).MerchantInsert), arg0, arg1)
}

// MerchantListGetData mocks base method.
func (m *MockIMerchant) MerchantListGetData(arg0 *param.MerchantListGet) ([]merchant.Merchant, *response.Status) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MerchantListGetData", arg0)
	ret0, _ := ret[0].([]merchant.Merchant)
	ret1, _ := ret[1].(*response.Status)
	return ret0, ret1
}

// MerchantListGetData indicates an expected call of MerchantListGetData.
func (mr *MockIMerchantMockRecorder) MerchantListGetData(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MerchantListGetData", reflect.TypeOf((*MockIMerchant)(nil).MerchantListGetData), arg0)
}

// MerchantListGetTotal mocks base method.
func (m *MockIMerchant) MerchantListGetTotal(arg0 *param.MerchantListGet) (int64, *response.Status) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MerchantListGetTotal", arg0)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(*response.Status)
	return ret0, ret1
}

// MerchantListGetTotal indicates an expected call of MerchantListGetTotal.
func (mr *MockIMerchantMockRecorder) MerchantListGetTotal(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MerchantListGetTotal", reflect.TypeOf((*MockIMerchant)(nil).MerchantListGetTotal), arg0)
}

// MerchantUpdate mocks base method.
func (m *MockIMerchant) MerchantUpdate(arg0 *ctx.Ctx, arg1 *merchant.Merchant) (bool, *response.Status) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MerchantUpdate", arg0, arg1)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(*response.Status)
	return ret0, ret1
}

// MerchantUpdate indicates an expected call of MerchantUpdate.
func (mr *MockIMerchantMockRecorder) MerchantUpdate(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MerchantUpdate", reflect.TypeOf((*MockIMerchant)(nil).MerchantUpdate), arg0, arg1)
}
