// Code generated by MockGen. DO NOT EDIT.
// Source: transaction.go
//
// Generated by this command:
//
//	mockgen -source transaction.go -package mock -destination ./mock/transaction.go
//

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	dto "github.com/dedyf5/resik/core/transaction/dto"
	ctx "github.com/dedyf5/resik/ctx"
	transaction "github.com/dedyf5/resik/entities/transaction"
	param "github.com/dedyf5/resik/entities/transaction/param"
	response "github.com/dedyf5/resik/pkg/response"
	gomock "go.uber.org/mock/gomock"
)

// MockIService is a mock of IService interface.
type MockIService struct {
	ctrl     *gomock.Controller
	recorder *MockIServiceMockRecorder
	isgomock struct{}
}

// MockIServiceMockRecorder is the mock recorder for MockIService.
type MockIServiceMockRecorder struct {
	mock *MockIService
}

// NewMockIService creates a new mock instance.
func NewMockIService(ctrl *gomock.Controller) *MockIService {
	mock := &MockIService{ctrl: ctrl}
	mock.recorder = &MockIServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIService) EXPECT() *MockIServiceMockRecorder {
	return m.recorder
}

// BranchOmzetGet mocks base method.
func (m *MockIService) BranchOmzetGet(arg0 *param.BranchOmzetGet) (*dto.BranchOmzet, *response.Status) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BranchOmzetGet", arg0)
	ret0, _ := ret[0].(*dto.BranchOmzet)
	ret1, _ := ret[1].(*response.Status)
	return ret0, ret1
}

// BranchOmzetGet indicates an expected call of BranchOmzetGet.
func (mr *MockIServiceMockRecorder) BranchOmzetGet(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BranchOmzetGet", reflect.TypeOf((*MockIService)(nil).BranchOmzetGet), arg0)
}

// OrganizationOmzetGet mocks base method.
func (m *MockIService) OrganizationOmzetGet(arg0 *param.OrganizationOmzetGet) (*dto.OrganizationOmzet, *response.Status) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OrganizationOmzetGet", arg0)
	ret0, _ := ret[0].(*dto.OrganizationOmzet)
	ret1, _ := ret[1].(*response.Status)
	return ret0, ret1
}

// OrganizationOmzetGet indicates an expected call of OrganizationOmzetGet.
func (mr *MockIServiceMockRecorder) OrganizationOmzetGet(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OrganizationOmzetGet", reflect.TypeOf((*MockIService)(nil).OrganizationOmzetGet), arg0)
}

// TransactionGetByPublicID mocks base method.
func (m *MockIService) TransactionGetByPublicID(arg0 *param.TransactionGet) (*dto.Transaction, *response.Status) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TransactionGetByPublicID", arg0)
	ret0, _ := ret[0].(*dto.Transaction)
	ret1, _ := ret[1].(*response.Status)
	return ret0, ret1
}

// TransactionGetByPublicID indicates an expected call of TransactionGetByPublicID.
func (mr *MockIServiceMockRecorder) TransactionGetByPublicID(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TransactionGetByPublicID", reflect.TypeOf((*MockIService)(nil).TransactionGetByPublicID), arg0)
}

// TransactionInsert mocks base method.
func (m *MockIService) TransactionInsert(arg0 *ctx.Ctx, arg1 *transaction.Transaction) (bool, *response.Status) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TransactionInsert", arg0, arg1)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(*response.Status)
	return ret0, ret1
}

// TransactionInsert indicates an expected call of TransactionInsert.
func (mr *MockIServiceMockRecorder) TransactionInsert(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TransactionInsert", reflect.TypeOf((*MockIService)(nil).TransactionInsert), arg0, arg1)
}

// TransactionsGet mocks base method.
func (m *MockIService) TransactionsGet(arg0 *param.TransactionsGet) (*dto.TransactionsResult, *response.Status) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TransactionsGet", arg0)
	ret0, _ := ret[0].(*dto.TransactionsResult)
	ret1, _ := ret[1].(*response.Status)
	return ret0, ret1
}

// TransactionsGet indicates an expected call of TransactionsGet.
func (mr *MockIServiceMockRecorder) TransactionsGet(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TransactionsGet", reflect.TypeOf((*MockIService)(nil).TransactionsGet), arg0)
}
