// Code generated by MockGen. DO NOT EDIT.
// Source: hash.go
//
// Generated by this command:
//
//	mockgen -source hash.go -package mock -destination ./mock/hash.go
//

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockIHash is a mock of IHash interface.
type MockIHash struct {
	ctrl     *gomock.Controller
	recorder *MockIHashMockRecorder
	isgomock struct{}
}

// MockIHashMockRecorder is the mock recorder for MockIHash.
type MockIHashMockRecorder struct {
	mock *MockIHash
}

// NewMockIHash creates a new mock instance.
func NewMockIHash(ctrl *gomock.Controller) *MockIHash {
	mock := &MockIHash{ctrl: ctrl}
	mock.recorder = &MockIHashMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIHash) EXPECT() *MockIHashMockRecorder {
	return m.recorder
}

// Compare mocks base method.
func (m *MockIHash) Compare(password, encodedHash string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Compare", password, encodedHash)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Compare indicates an expected call of Compare.
func (mr *MockIHashMockRecorder) Compare(password, encodedHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Compare", reflect.TypeOf((*MockIHash)(nil).Compare), password, encodedHash)
}

// Hash mocks base method.
func (m *MockIHash) Hash(password string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Hash", password)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Hash indicates an expected call of Hash.
func (mr *MockIHashMockRecorder) Hash(password any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Hash", reflect.TypeOf((*MockIHash)(nil).Hash), password)
}
